# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /bwrcq/C/vikramj/dsp-chiplet-to/chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-config.xdc

# XDC: /bwrcq/C/vikramj/dsp-chiplet-to/chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-master.xdc

# XDC: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/chipyard.fpga.nexysvideo.NexysVideoHarness.BringupNexysVideoConfig.shell.sdc

# XDC: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/chipyard.fpga.nexysvideo.NexysVideoHarness.BringupNexysVideoConfig.shell.xdc

# IP: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==harnessSysPLLNode || ORIG_REF_NAME==harnessSysPLLNode} -quiet] -quiet

# IP: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/nexysvideomig/nexysvideomig.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nexysvideomig || ORIG_REF_NAME==nexysvideomig} -quiet] -quiet

# XDC: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==harnessSysPLLNode || ORIG_REF_NAME==harnessSysPLLNode} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==harnessSysPLLNode || ORIG_REF_NAME==harnessSysPLLNode} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==harnessSysPLLNode || ORIG_REF_NAME==harnessSysPLLNode} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_ooc.xdc

# XDC: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/nexysvideomig/nexysvideomig/user_design/constraints/nexysvideomig.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nexysvideomig || ORIG_REF_NAME==nexysvideomig} -quiet] -quiet

# XDC: /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/nexysvideomig/nexysvideomig/user_design/constraints/nexysvideomig_ooc.xdc
