# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/NexysVideoHarness.runs/synth_1/NexysVideoHarness.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/NexysVideoHarness.cache/wt [current_project]
set_property parent.project_path /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/NexysVideoHarness.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/bwrcq/home/vikramj/Downloads/vivado_board_files/vivado-boards-master/new/board_files} [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip [current_project]
update_ip_catalog
set_property ip_output_repo /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/NexysVideoHarness.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AXI4AsyncCrossingSink.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AXI4AsyncCrossingSource.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AXI4Deinterleaver.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AXI4IdIndexer.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AXI4UserYanker.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueue.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSink.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSink_2.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSink_3.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSink_4.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSink_5.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSource.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSource_1.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSource_2.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSource_4.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncQueueSource_5.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncResetReg.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncResetRegVec_w13_i0.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncResetSynchronizerPrimitiveShiftReg_d3_i0.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0_4.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncResetSynchronizerShiftReg_w4_d3_i0.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AsyncValidSync.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ChipTop.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockCrossingReg_w1.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockCrossingReg_w6.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockCrossingReg_w61.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockCrossingReg_w71.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockCrossingReg_w73.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockGroupAggregator_7.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockGroupCombiner.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockGroupParameterModifier.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockGroupParameterModifier_1.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockGroupResetSynchronizer.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockGroup_1.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockSinkDomain.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ClockSinkDomain_1.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/CoherenceManagerWrapper.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/DecoupledSerialPhy.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/DigitalTop.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/FixedClockBroadcast.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/FixedClockBroadcast_3.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/FlitToPhit.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/FrontBus.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/GenericDeserializer.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/GenericDeserializer_1.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/GenericDeserializer_2.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/GenericDeserializer_3.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/GenericSerializer.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/GenericSerializer_1.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/GenericSerializer_2.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/GenericSerializer_3.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/MemoryBus.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/OffchipBus.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/PhitArbiter.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/PhitDemux.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/PhitToFlit.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ProbePicker.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_1.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_2.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_20.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_3.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_4.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_52.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_53.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_54.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_55.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_56.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_60.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_65.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_68.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/Queue_69.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ResetCatchAndSync_d3.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ResetWrangler.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/SerialWidthAdapter.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/SerialWidthAggregator.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/SerialWidthSlicer.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/SystemBus.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLAFromBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLAToBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBFromBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBToBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBroadcast.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBroadcastTracker.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBroadcastTracker_1.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBroadcastTracker_2.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBroadcastTracker_3.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBuffer.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBuffer_3.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLBuffer_4.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLCFromBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLCToBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLDFromBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLDToBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLEFromBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLEToBeat.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLInterconnectCoupler_5.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLInterconnectCoupler_7.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLInterconnectCoupler_9.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLProbeBlocker.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLSerdesser.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLSourceAdjuster.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLSourceCombiner.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLSourceShrinker.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLSwitch.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLToAXI4.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLXbar.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TLXbar_3.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/TSIToTileLink.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/UARTRx.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/UARTToSerial.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/UARTTx.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/XilinxNexysVideoMIG.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/XilinxNexysVideoMIGIsland.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_2x118.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_2x122.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_2x123.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_2x79.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_2x84.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_2x85.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_8x72.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_8x79.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_8x8.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/ram_flit_8x16.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/sourceIdMap_16x11.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/sourceIdMap_64x9.sv
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/NexysVideoHarness.sv
}
read_verilog -library xil_defaultlib {
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/AnalogToUInt_1.v
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/GenericDigitalOutIOCell.v
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/PowerOnResetFPGAOnly.v
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/UIntToAnalog_1.v
  /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/gen-collateral/plusarg_reader.v
}
read_ip -quiet /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode.xci
set_property used_in_implementation false [get_files -all /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_board.xdc]
set_property used_in_implementation false [get_files -all /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode.xdc]
set_property used_in_implementation false [get_files -all /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_late.xdc]
set_property used_in_implementation false [get_files -all /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_ooc.xdc]

read_ip -quiet /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/nexysvideomig/nexysvideomig.xci
set_property used_in_implementation false [get_files -all /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/nexysvideomig/nexysvideomig/user_design/constraints/nexysvideomig.xdc]
set_property used_in_implementation false [get_files -all /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/obj/ip/nexysvideomig/nexysvideomig/user_design/constraints/nexysvideomig_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /bwrcq/C/vikramj/dsp-chiplet-to/chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-config.xdc
set_property used_in_implementation false [get_files /bwrcq/C/vikramj/dsp-chiplet-to/chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-config.xdc]

read_xdc /bwrcq/C/vikramj/dsp-chiplet-to/chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-master.xdc
set_property used_in_implementation false [get_files /bwrcq/C/vikramj/dsp-chiplet-to/chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-master.xdc]

read_xdc /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/chipyard.fpga.nexysvideo.NexysVideoHarness.BringupNexysVideoConfig.shell.sdc
set_property used_in_implementation false [get_files /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/chipyard.fpga.nexysvideo.NexysVideoHarness.BringupNexysVideoConfig.shell.sdc]

read_xdc /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/chipyard.fpga.nexysvideo.NexysVideoHarness.BringupNexysVideoConfig.shell.xdc
set_property used_in_implementation false [get_files /bwrcq/C/vikramj/Cygnus-Bringup/cygnus-fpga-mig/chipyard.fpga.nexysvideo.NexysVideoHarness.BringupNexysVideoConfig.shell.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top NexysVideoHarness -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NexysVideoHarness.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NexysVideoHarness_utilization_synth.rpt -pb NexysVideoHarness_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
