// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ClockSinkDomain(
  output        auto_serdesser_manager_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_serdesser_manager_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_serdesser_manager_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_serdesser_manager_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_serdesser_manager_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_serdesser_manager_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [30:0] auto_serdesser_manager_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_serdesser_manager_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_serdesser_manager_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_serdesser_manager_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_serdesser_manager_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_serdesser_manager_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_serdesser_manager_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [1:0]  auto_serdesser_manager_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_serdesser_manager_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_serdesser_manager_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_serdesser_manager_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_serdesser_manager_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_serdesser_manager_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_serdesser_manager_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_serdesser_client_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_serdesser_client_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_serdesser_client_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_serdesser_client_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_serdesser_client_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_serdesser_client_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [31:0] auto_serdesser_client_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_serdesser_client_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_serdesser_client_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_serdesser_client_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_serdesser_client_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_serdesser_client_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_serdesser_client_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_serdesser_client_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_serdesser_client_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_serdesser_client_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_serdesser_client_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_serdesser_client_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_serdesser_client_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_serdesser_client_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_serial_tl_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_clock_in_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        serial_tl_0_in_ready,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:164:24]
  input         serial_tl_0_in_valid,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:164:24]
  input         serial_tl_0_in_bits_phit,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:164:24]
  input         serial_tl_0_out_ready,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:164:24]
  output        serial_tl_0_out_valid,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:164:24]
  output        serial_tl_0_out_bits_phit,	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:164:24]
  output        serial_tl_0_clock_out	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:164:24]
);

  wire        _phy_io_outer_reset_catcher_io_sync_reset;	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  wire        _phy_io_inner_ser_0_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire [15:0] _phy_io_inner_ser_0_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire        _phy_io_inner_ser_1_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire [15:0] _phy_io_inner_ser_1_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire        _phy_io_inner_ser_1_out_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire        _phy_io_inner_ser_2_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire [15:0] _phy_io_inner_ser_2_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire        _phy_io_inner_ser_2_out_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire        _phy_io_inner_ser_3_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire [15:0] _phy_io_inner_ser_3_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire        _phy_io_inner_ser_3_out_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire        _phy_io_inner_ser_4_in_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire [15:0] _phy_io_inner_ser_4_in_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire        _phy_io_inner_ser_4_out_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  wire        _serdesser_io_ser_0_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire [15:0] _serdesser_io_ser_0_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_1_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_1_out_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire [15:0] _serdesser_io_ser_1_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_2_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_2_out_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire [15:0] _serdesser_io_ser_2_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_3_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_3_out_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire [15:0] _serdesser_io_ser_3_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_4_in_ready;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire        _serdesser_io_ser_4_out_valid;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  wire [15:0] _serdesser_io_ser_4_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  TLSerdesser serdesser (	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .clock                          (auto_clock_in_clock),
    .reset                          (auto_clock_in_reset),
    .auto_manager_in_a_ready        (auto_serdesser_manager_in_a_ready),
    .auto_manager_in_a_valid        (auto_serdesser_manager_in_a_valid),
    .auto_manager_in_a_bits_opcode  (auto_serdesser_manager_in_a_bits_opcode),
    .auto_manager_in_a_bits_param   (auto_serdesser_manager_in_a_bits_param),
    .auto_manager_in_a_bits_size    (auto_serdesser_manager_in_a_bits_size),
    .auto_manager_in_a_bits_source  (auto_serdesser_manager_in_a_bits_source),
    .auto_manager_in_a_bits_address (auto_serdesser_manager_in_a_bits_address),
    .auto_manager_in_a_bits_mask    (auto_serdesser_manager_in_a_bits_mask),
    .auto_manager_in_a_bits_data    (auto_serdesser_manager_in_a_bits_data),
    .auto_manager_in_a_bits_corrupt (auto_serdesser_manager_in_a_bits_corrupt),
    .auto_manager_in_d_ready        (auto_serdesser_manager_in_d_ready),
    .auto_manager_in_d_valid        (auto_serdesser_manager_in_d_valid),
    .auto_manager_in_d_bits_opcode  (auto_serdesser_manager_in_d_bits_opcode),
    .auto_manager_in_d_bits_param   (auto_serdesser_manager_in_d_bits_param),
    .auto_manager_in_d_bits_size    (auto_serdesser_manager_in_d_bits_size),
    .auto_manager_in_d_bits_source  (auto_serdesser_manager_in_d_bits_source),
    .auto_manager_in_d_bits_sink    (auto_serdesser_manager_in_d_bits_sink),
    .auto_manager_in_d_bits_denied  (auto_serdesser_manager_in_d_bits_denied),
    .auto_manager_in_d_bits_data    (auto_serdesser_manager_in_d_bits_data),
    .auto_manager_in_d_bits_corrupt (auto_serdesser_manager_in_d_bits_corrupt),
    .auto_client_out_a_ready        (auto_serdesser_client_out_a_ready),
    .auto_client_out_a_valid        (auto_serdesser_client_out_a_valid),
    .auto_client_out_a_bits_opcode  (auto_serdesser_client_out_a_bits_opcode),
    .auto_client_out_a_bits_param   (auto_serdesser_client_out_a_bits_param),
    .auto_client_out_a_bits_size    (auto_serdesser_client_out_a_bits_size),
    .auto_client_out_a_bits_source  (auto_serdesser_client_out_a_bits_source),
    .auto_client_out_a_bits_address (auto_serdesser_client_out_a_bits_address),
    .auto_client_out_a_bits_mask    (auto_serdesser_client_out_a_bits_mask),
    .auto_client_out_a_bits_data    (auto_serdesser_client_out_a_bits_data),
    .auto_client_out_a_bits_corrupt (auto_serdesser_client_out_a_bits_corrupt),
    .auto_client_out_d_ready        (auto_serdesser_client_out_d_ready),
    .auto_client_out_d_valid        (auto_serdesser_client_out_d_valid),
    .auto_client_out_d_bits_opcode  (auto_serdesser_client_out_d_bits_opcode),
    .auto_client_out_d_bits_param   (auto_serdesser_client_out_d_bits_param),
    .auto_client_out_d_bits_size    (auto_serdesser_client_out_d_bits_size),
    .auto_client_out_d_bits_source  (auto_serdesser_client_out_d_bits_source),
    .auto_client_out_d_bits_sink    (auto_serdesser_client_out_d_bits_sink),
    .auto_client_out_d_bits_denied  (auto_serdesser_client_out_d_bits_denied),
    .auto_client_out_d_bits_data    (auto_serdesser_client_out_d_bits_data),
    .auto_client_out_d_bits_corrupt (auto_serdesser_client_out_d_bits_corrupt),
    .io_ser_0_in_ready              (_serdesser_io_ser_0_in_ready),
    .io_ser_0_in_valid              (_phy_io_inner_ser_0_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_0_in_bits_flit          (_phy_io_inner_ser_0_in_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_0_out_bits_flit         (_serdesser_io_ser_0_out_bits_flit),
    .io_ser_1_in_ready              (_serdesser_io_ser_1_in_ready),
    .io_ser_1_in_valid              (_phy_io_inner_ser_1_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_1_in_bits_flit          (_phy_io_inner_ser_1_in_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_1_out_ready             (_phy_io_inner_ser_1_out_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_1_out_valid             (_serdesser_io_ser_1_out_valid),
    .io_ser_1_out_bits_flit         (_serdesser_io_ser_1_out_bits_flit),
    .io_ser_2_in_ready              (_serdesser_io_ser_2_in_ready),
    .io_ser_2_in_valid              (_phy_io_inner_ser_2_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_2_in_bits_flit          (_phy_io_inner_ser_2_in_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_2_out_ready             (_phy_io_inner_ser_2_out_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_2_out_valid             (_serdesser_io_ser_2_out_valid),
    .io_ser_2_out_bits_flit         (_serdesser_io_ser_2_out_bits_flit),
    .io_ser_3_in_ready              (_serdesser_io_ser_3_in_ready),
    .io_ser_3_in_valid              (_phy_io_inner_ser_3_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_3_in_bits_flit          (_phy_io_inner_ser_3_in_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_3_out_ready             (_phy_io_inner_ser_3_out_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_3_out_valid             (_serdesser_io_ser_3_out_valid),
    .io_ser_3_out_bits_flit         (_serdesser_io_ser_3_out_bits_flit),
    .io_ser_4_in_ready              (_serdesser_io_ser_4_in_ready),
    .io_ser_4_in_valid              (_phy_io_inner_ser_4_in_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_4_in_bits_flit          (_phy_io_inner_ser_4_in_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_4_out_ready             (_phy_io_inner_ser_4_out_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_ser_4_out_valid             (_serdesser_io_ser_4_out_valid),
    .io_ser_4_out_bits_flit         (_serdesser_io_ser_4_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  DecoupledSerialPhy phy (	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
    .io_outer_clock               (auto_serial_tl_clock_in_clock),
    .io_outer_reset               (_phy_io_outer_reset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .io_inner_clock               (auto_clock_in_clock),
    .io_inner_reset               (auto_clock_in_reset),
    .io_outer_ser_in_ready        (serial_tl_0_in_ready),
    .io_outer_ser_in_valid        (serial_tl_0_in_valid),
    .io_outer_ser_in_bits_phit    (serial_tl_0_in_bits_phit),
    .io_outer_ser_out_ready       (serial_tl_0_out_ready),
    .io_outer_ser_out_valid       (serial_tl_0_out_valid),
    .io_outer_ser_out_bits_phit   (serial_tl_0_out_bits_phit),
    .io_inner_ser_0_in_ready      (_serdesser_io_ser_0_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_0_in_valid      (_phy_io_inner_ser_0_in_valid),
    .io_inner_ser_0_in_bits_flit  (_phy_io_inner_ser_0_in_bits_flit),
    .io_inner_ser_0_out_bits_flit (_serdesser_io_ser_0_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_1_in_ready      (_serdesser_io_ser_1_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_1_in_valid      (_phy_io_inner_ser_1_in_valid),
    .io_inner_ser_1_in_bits_flit  (_phy_io_inner_ser_1_in_bits_flit),
    .io_inner_ser_1_out_ready     (_phy_io_inner_ser_1_out_ready),
    .io_inner_ser_1_out_valid     (_serdesser_io_ser_1_out_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_1_out_bits_flit (_serdesser_io_ser_1_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_2_in_ready      (_serdesser_io_ser_2_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_2_in_valid      (_phy_io_inner_ser_2_in_valid),
    .io_inner_ser_2_in_bits_flit  (_phy_io_inner_ser_2_in_bits_flit),
    .io_inner_ser_2_out_ready     (_phy_io_inner_ser_2_out_ready),
    .io_inner_ser_2_out_valid     (_serdesser_io_ser_2_out_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_2_out_bits_flit (_serdesser_io_ser_2_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_3_in_ready      (_serdesser_io_ser_3_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_3_in_valid      (_phy_io_inner_ser_3_in_valid),
    .io_inner_ser_3_in_bits_flit  (_phy_io_inner_ser_3_in_bits_flit),
    .io_inner_ser_3_out_ready     (_phy_io_inner_ser_3_out_ready),
    .io_inner_ser_3_out_valid     (_serdesser_io_ser_3_out_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_3_out_bits_flit (_serdesser_io_ser_3_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_4_in_ready      (_serdesser_io_ser_4_in_ready),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_4_in_valid      (_phy_io_inner_ser_4_in_valid),
    .io_inner_ser_4_in_bits_flit  (_phy_io_inner_ser_4_in_bits_flit),
    .io_inner_ser_4_out_ready     (_phy_io_inner_ser_4_out_ready),
    .io_inner_ser_4_out_valid     (_serdesser_io_ser_4_out_valid),	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
    .io_inner_ser_4_out_bits_flit (_serdesser_io_ser_4_out_bits_flit)	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:129:50]
  );	// @[generators/testchipip/src/main/scala/serdes/PeripheryTLSerial.scala:172:27]
  ResetCatchAndSync_d3 phy_io_outer_reset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (auto_serial_tl_clock_in_clock),
    .reset         (auto_clock_in_reset),
    .io_sync_reset (_phy_io_outer_reset_catcher_io_sync_reset)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  assign serial_tl_0_clock_out = auto_serial_tl_clock_in_clock;
endmodule

