// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module DecoupledSerialPhy(
  input         io_outer_clock,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_outer_reset,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_clock,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_reset,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_outer_ser_in_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_outer_ser_in_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_outer_ser_in_bits_phit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_outer_ser_out_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_outer_ser_out_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_outer_ser_out_bits_phit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_ser_0_in_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_inner_ser_0_in_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output [15:0] io_inner_ser_0_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input  [15:0] io_inner_ser_0_out_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_ser_1_in_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_inner_ser_1_in_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output [15:0] io_inner_ser_1_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_inner_ser_1_out_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_ser_1_out_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input  [15:0] io_inner_ser_1_out_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_ser_2_in_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_inner_ser_2_in_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output [15:0] io_inner_ser_2_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_inner_ser_2_out_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_ser_2_out_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input  [15:0] io_inner_ser_2_out_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_ser_3_in_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_inner_ser_3_in_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output [15:0] io_inner_ser_3_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_inner_ser_3_out_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_ser_3_out_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input  [15:0] io_inner_ser_3_out_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_ser_4_in_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_inner_ser_4_in_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output [15:0] io_inner_ser_4_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  output        io_inner_ser_4_out_ready,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input         io_inner_ser_4_out_valid,	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
  input  [15:0] io_inner_ser_4_out_bits_flit	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:14:14]
);

  wire        _in_demux_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_0_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_0_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_1_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_1_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_2_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_2_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_3_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_3_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_4_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_demux_io_out_4_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  wire        _in_phits_io_inner_ser_4_in_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _in_phits_io_inner_ser_4_in_phit2flit_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_io_inner_ser_4_in_phit2flit_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire [15:0] _in_phits_io_inner_ser_4_in_phit2flit_io_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_in_async_4_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_4_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_4_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_io_inner_ser_3_in_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _in_phits_io_inner_ser_3_in_phit2flit_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_io_inner_ser_3_in_phit2flit_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire [15:0] _in_phits_io_inner_ser_3_in_phit2flit_io_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_in_async_3_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_3_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_3_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_io_inner_ser_2_in_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _in_phits_io_inner_ser_2_in_phit2flit_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_io_inner_ser_2_in_phit2flit_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire [15:0] _in_phits_io_inner_ser_2_in_phit2flit_io_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_in_async_2_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_2_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_2_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_io_inner_ser_1_in_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _in_phits_io_inner_ser_1_in_phit2flit_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_io_inner_ser_1_in_phit2flit_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire [15:0] _in_phits_io_inner_ser_1_in_phit2flit_io_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_in_async_1_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_1_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_1_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_io_inner_ser_0_in_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _in_phits_io_inner_ser_0_in_phit2flit_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_io_inner_ser_0_in_phit2flit_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire [15:0] _in_phits_io_inner_ser_0_in_phit2flit_io_out_bits_flit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  wire        _in_phits_in_async_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _in_phits_in_async_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  wire        _out_arb_io_in_0_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
  wire        _out_arb_io_in_1_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
  wire        _out_arb_io_in_2_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
  wire        _out_arb_io_in_3_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
  wire        _out_arb_io_in_4_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
  wire        _out_arb_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
  wire        _out_phits_out_async_io_enq_flit2phit_4_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_4_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_4_io_out_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_q_4_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire [15:0] _out_phits_out_async_io_enq_q_4_io_deq_bits_flit;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _out_phits_out_async_4_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_4_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_4_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_io_enq_flit2phit_3_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_3_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_3_io_out_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_q_3_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire [15:0] _out_phits_out_async_io_enq_q_3_io_deq_bits_flit;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _out_phits_out_async_3_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_3_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_3_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_io_enq_flit2phit_2_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_2_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_2_io_out_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_q_2_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire [15:0] _out_phits_out_async_io_enq_q_2_io_deq_bits_flit;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _out_phits_out_async_2_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_2_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_2_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_io_enq_flit2phit_1_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_1_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_1_io_out_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_q_1_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire [15:0] _out_phits_out_async_io_enq_q_1_io_deq_bits_flit;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _out_phits_out_async_1_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_1_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_1_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_io_enq_flit2phit_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_flit2phit_io_out_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  wire        _out_phits_out_async_io_enq_q_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire [15:0] _out_phits_out_async_io_enq_q_io_deq_bits_flit;	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  wire        _out_phits_out_async_io_enq_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  wire        _out_phits_out_async_io_deq_bits_phit;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  AsyncQueue out_phits_out_async (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_enq_clock     (io_inner_clock),
    .io_enq_reset     (io_inner_reset),
    .io_enq_ready     (_out_phits_out_async_io_enq_ready),
    .io_enq_valid     (_out_phits_out_async_io_enq_flit2phit_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_enq_bits_phit (_out_phits_out_async_io_enq_flit2phit_io_out_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_clock     (io_outer_clock),
    .io_deq_reset     (io_outer_reset),
    .io_deq_ready     (_out_arb_io_in_0_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
    .io_deq_valid     (_out_phits_out_async_io_deq_valid),
    .io_deq_bits_phit (_out_phits_out_async_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  Queue_69 out_phits_out_async_io_enq_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (/* unused */),
    .io_enq_valid     (1'h0),
    .io_enq_bits_flit (io_inner_ser_0_out_bits_flit),
    .io_deq_ready     (_out_phits_out_async_io_enq_flit2phit_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_valid     (_out_phits_out_async_io_enq_q_io_deq_valid),
    .io_deq_bits_flit (_out_phits_out_async_io_enq_q_io_deq_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  FlitToPhit out_phits_out_async_io_enq_flit2phit (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_out_phits_out_async_io_enq_flit2phit_io_in_ready),
    .io_in_valid      (_out_phits_out_async_io_enq_q_io_deq_valid),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_in_bits_flit  (_out_phits_out_async_io_enq_q_io_deq_bits_flit),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_ready     (_out_phits_out_async_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_out_valid     (_out_phits_out_async_io_enq_flit2phit_io_out_valid),
    .io_out_bits_phit (_out_phits_out_async_io_enq_flit2phit_io_out_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  AsyncQueue out_phits_out_async_1 (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_enq_clock     (io_inner_clock),
    .io_enq_reset     (io_inner_reset),
    .io_enq_ready     (_out_phits_out_async_1_io_enq_ready),
    .io_enq_valid     (_out_phits_out_async_io_enq_flit2phit_1_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_enq_bits_phit (_out_phits_out_async_io_enq_flit2phit_1_io_out_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_clock     (io_outer_clock),
    .io_deq_reset     (io_outer_reset),
    .io_deq_ready     (_out_arb_io_in_1_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
    .io_deq_valid     (_out_phits_out_async_1_io_deq_valid),
    .io_deq_bits_phit (_out_phits_out_async_1_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  Queue_69 out_phits_out_async_io_enq_q_1 (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (io_inner_ser_1_out_ready),
    .io_enq_valid     (io_inner_ser_1_out_valid),
    .io_enq_bits_flit (io_inner_ser_1_out_bits_flit),
    .io_deq_ready     (_out_phits_out_async_io_enq_flit2phit_1_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_valid     (_out_phits_out_async_io_enq_q_1_io_deq_valid),
    .io_deq_bits_flit (_out_phits_out_async_io_enq_q_1_io_deq_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  FlitToPhit out_phits_out_async_io_enq_flit2phit_1 (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_out_phits_out_async_io_enq_flit2phit_1_io_in_ready),
    .io_in_valid      (_out_phits_out_async_io_enq_q_1_io_deq_valid),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_in_bits_flit  (_out_phits_out_async_io_enq_q_1_io_deq_bits_flit),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_ready     (_out_phits_out_async_1_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_out_valid     (_out_phits_out_async_io_enq_flit2phit_1_io_out_valid),
    .io_out_bits_phit (_out_phits_out_async_io_enq_flit2phit_1_io_out_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  AsyncQueue out_phits_out_async_2 (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_enq_clock     (io_inner_clock),
    .io_enq_reset     (io_inner_reset),
    .io_enq_ready     (_out_phits_out_async_2_io_enq_ready),
    .io_enq_valid     (_out_phits_out_async_io_enq_flit2phit_2_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_enq_bits_phit (_out_phits_out_async_io_enq_flit2phit_2_io_out_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_clock     (io_outer_clock),
    .io_deq_reset     (io_outer_reset),
    .io_deq_ready     (_out_arb_io_in_2_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
    .io_deq_valid     (_out_phits_out_async_2_io_deq_valid),
    .io_deq_bits_phit (_out_phits_out_async_2_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  Queue_69 out_phits_out_async_io_enq_q_2 (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (io_inner_ser_2_out_ready),
    .io_enq_valid     (io_inner_ser_2_out_valid),
    .io_enq_bits_flit (io_inner_ser_2_out_bits_flit),
    .io_deq_ready     (_out_phits_out_async_io_enq_flit2phit_2_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_valid     (_out_phits_out_async_io_enq_q_2_io_deq_valid),
    .io_deq_bits_flit (_out_phits_out_async_io_enq_q_2_io_deq_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  FlitToPhit out_phits_out_async_io_enq_flit2phit_2 (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_out_phits_out_async_io_enq_flit2phit_2_io_in_ready),
    .io_in_valid      (_out_phits_out_async_io_enq_q_2_io_deq_valid),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_in_bits_flit  (_out_phits_out_async_io_enq_q_2_io_deq_bits_flit),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_ready     (_out_phits_out_async_2_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_out_valid     (_out_phits_out_async_io_enq_flit2phit_2_io_out_valid),
    .io_out_bits_phit (_out_phits_out_async_io_enq_flit2phit_2_io_out_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  AsyncQueue out_phits_out_async_3 (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_enq_clock     (io_inner_clock),
    .io_enq_reset     (io_inner_reset),
    .io_enq_ready     (_out_phits_out_async_3_io_enq_ready),
    .io_enq_valid     (_out_phits_out_async_io_enq_flit2phit_3_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_enq_bits_phit (_out_phits_out_async_io_enq_flit2phit_3_io_out_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_clock     (io_outer_clock),
    .io_deq_reset     (io_outer_reset),
    .io_deq_ready     (_out_arb_io_in_3_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
    .io_deq_valid     (_out_phits_out_async_3_io_deq_valid),
    .io_deq_bits_phit (_out_phits_out_async_3_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  Queue_69 out_phits_out_async_io_enq_q_3 (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (io_inner_ser_3_out_ready),
    .io_enq_valid     (io_inner_ser_3_out_valid),
    .io_enq_bits_flit (io_inner_ser_3_out_bits_flit),
    .io_deq_ready     (_out_phits_out_async_io_enq_flit2phit_3_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_valid     (_out_phits_out_async_io_enq_q_3_io_deq_valid),
    .io_deq_bits_flit (_out_phits_out_async_io_enq_q_3_io_deq_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  FlitToPhit out_phits_out_async_io_enq_flit2phit_3 (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_out_phits_out_async_io_enq_flit2phit_3_io_in_ready),
    .io_in_valid      (_out_phits_out_async_io_enq_q_3_io_deq_valid),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_in_bits_flit  (_out_phits_out_async_io_enq_q_3_io_deq_bits_flit),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_ready     (_out_phits_out_async_3_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_out_valid     (_out_phits_out_async_io_enq_flit2phit_3_io_out_valid),
    .io_out_bits_phit (_out_phits_out_async_io_enq_flit2phit_3_io_out_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  AsyncQueue out_phits_out_async_4 (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_enq_clock     (io_inner_clock),
    .io_enq_reset     (io_inner_reset),
    .io_enq_ready     (_out_phits_out_async_4_io_enq_ready),
    .io_enq_valid     (_out_phits_out_async_io_enq_flit2phit_4_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_enq_bits_phit (_out_phits_out_async_io_enq_flit2phit_4_io_out_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_clock     (io_outer_clock),
    .io_deq_reset     (io_outer_reset),
    .io_deq_ready     (_out_arb_io_in_4_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
    .io_deq_valid     (_out_phits_out_async_4_io_deq_valid),
    .io_deq_bits_phit (_out_phits_out_async_4_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
  Queue_69 out_phits_out_async_io_enq_q_4 (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (io_inner_ser_4_out_ready),
    .io_enq_valid     (io_inner_ser_4_out_valid),
    .io_enq_bits_flit (io_inner_ser_4_out_bits_flit),
    .io_deq_ready     (_out_phits_out_async_io_enq_flit2phit_4_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .io_deq_valid     (_out_phits_out_async_io_enq_q_4_io_deq_valid),
    .io_deq_bits_flit (_out_phits_out_async_io_enq_q_4_io_deq_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  FlitToPhit out_phits_out_async_io_enq_flit2phit_4 (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_out_phits_out_async_io_enq_flit2phit_4_io_in_ready),
    .io_in_valid      (_out_phits_out_async_io_enq_q_4_io_deq_valid),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_in_bits_flit  (_out_phits_out_async_io_enq_q_4_io_deq_bits_flit),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_ready     (_out_phits_out_async_4_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_out_valid     (_out_phits_out_async_io_enq_flit2phit_4_io_out_valid),
    .io_out_bits_phit (_out_phits_out_async_io_enq_flit2phit_4_io_out_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:92:27]
  PhitArbiter out_arb (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
    .clock             (io_outer_clock),
    .reset             (io_outer_reset),
    .io_in_0_ready     (_out_arb_io_in_0_ready),
    .io_in_0_valid     (_out_phits_out_async_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_in_0_bits_phit (_out_phits_out_async_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_in_1_ready     (_out_arb_io_in_1_ready),
    .io_in_1_valid     (_out_phits_out_async_1_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_in_1_bits_phit (_out_phits_out_async_1_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_in_2_ready     (_out_arb_io_in_2_ready),
    .io_in_2_valid     (_out_phits_out_async_2_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_in_2_bits_phit (_out_phits_out_async_2_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_in_3_ready     (_out_arb_io_in_3_ready),
    .io_in_3_valid     (_out_phits_out_async_3_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_in_3_bits_phit (_out_phits_out_async_3_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_in_4_ready     (_out_arb_io_in_4_ready),
    .io_in_4_valid     (_out_phits_out_async_4_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_in_4_bits_phit (_out_phits_out_async_4_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:25:27]
    .io_out_ready      (io_outer_ser_out_ready),
    .io_out_valid      (_out_arb_io_out_valid),
    .io_out_bits_phit  (io_outer_ser_out_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11]
  AsyncQueue in_phits_in_async (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_enq_clock     (io_outer_clock),
    .io_enq_reset     (io_outer_reset),
    .io_enq_ready     (_in_phits_in_async_io_enq_ready),
    .io_enq_valid     (_in_demux_io_out_0_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_enq_bits_phit (_in_demux_io_out_0_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_deq_clock     (io_inner_clock),
    .io_deq_reset     (io_inner_reset),
    .io_deq_ready     (_in_phits_io_inner_ser_0_in_phit2flit_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_valid     (_in_phits_in_async_io_deq_valid),
    .io_deq_bits_phit (_in_phits_in_async_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  PhitToFlit in_phits_io_inner_ser_0_in_phit2flit (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_in_phits_io_inner_ser_0_in_phit2flit_io_in_ready),
    .io_in_valid      (_in_phits_in_async_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_in_bits_phit  (_in_phits_in_async_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_ready     (_in_phits_io_inner_ser_0_in_q_io_enq_ready),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_valid     (_in_phits_io_inner_ser_0_in_phit2flit_io_out_valid),
    .io_out_bits_flit (_in_phits_io_inner_ser_0_in_phit2flit_io_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  Queue_69 in_phits_io_inner_ser_0_in_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (_in_phits_io_inner_ser_0_in_q_io_enq_ready),
    .io_enq_valid     (_in_phits_io_inner_ser_0_in_phit2flit_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_enq_bits_flit (_in_phits_io_inner_ser_0_in_phit2flit_io_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_ready     (io_inner_ser_0_in_ready),
    .io_deq_valid     (io_inner_ser_0_in_valid),
    .io_deq_bits_flit (io_inner_ser_0_in_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  AsyncQueue in_phits_in_async_1 (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_enq_clock     (io_outer_clock),
    .io_enq_reset     (io_outer_reset),
    .io_enq_ready     (_in_phits_in_async_1_io_enq_ready),
    .io_enq_valid     (_in_demux_io_out_1_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_enq_bits_phit (_in_demux_io_out_1_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_deq_clock     (io_inner_clock),
    .io_deq_reset     (io_inner_reset),
    .io_deq_ready     (_in_phits_io_inner_ser_1_in_phit2flit_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_valid     (_in_phits_in_async_1_io_deq_valid),
    .io_deq_bits_phit (_in_phits_in_async_1_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  PhitToFlit in_phits_io_inner_ser_1_in_phit2flit (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_in_phits_io_inner_ser_1_in_phit2flit_io_in_ready),
    .io_in_valid      (_in_phits_in_async_1_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_in_bits_phit  (_in_phits_in_async_1_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_ready     (_in_phits_io_inner_ser_1_in_q_io_enq_ready),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_valid     (_in_phits_io_inner_ser_1_in_phit2flit_io_out_valid),
    .io_out_bits_flit (_in_phits_io_inner_ser_1_in_phit2flit_io_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  Queue_69 in_phits_io_inner_ser_1_in_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (_in_phits_io_inner_ser_1_in_q_io_enq_ready),
    .io_enq_valid     (_in_phits_io_inner_ser_1_in_phit2flit_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_enq_bits_flit (_in_phits_io_inner_ser_1_in_phit2flit_io_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_ready     (io_inner_ser_1_in_ready),
    .io_deq_valid     (io_inner_ser_1_in_valid),
    .io_deq_bits_flit (io_inner_ser_1_in_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  AsyncQueue in_phits_in_async_2 (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_enq_clock     (io_outer_clock),
    .io_enq_reset     (io_outer_reset),
    .io_enq_ready     (_in_phits_in_async_2_io_enq_ready),
    .io_enq_valid     (_in_demux_io_out_2_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_enq_bits_phit (_in_demux_io_out_2_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_deq_clock     (io_inner_clock),
    .io_deq_reset     (io_inner_reset),
    .io_deq_ready     (_in_phits_io_inner_ser_2_in_phit2flit_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_valid     (_in_phits_in_async_2_io_deq_valid),
    .io_deq_bits_phit (_in_phits_in_async_2_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  PhitToFlit in_phits_io_inner_ser_2_in_phit2flit (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_in_phits_io_inner_ser_2_in_phit2flit_io_in_ready),
    .io_in_valid      (_in_phits_in_async_2_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_in_bits_phit  (_in_phits_in_async_2_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_ready     (_in_phits_io_inner_ser_2_in_q_io_enq_ready),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_valid     (_in_phits_io_inner_ser_2_in_phit2flit_io_out_valid),
    .io_out_bits_flit (_in_phits_io_inner_ser_2_in_phit2flit_io_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  Queue_69 in_phits_io_inner_ser_2_in_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (_in_phits_io_inner_ser_2_in_q_io_enq_ready),
    .io_enq_valid     (_in_phits_io_inner_ser_2_in_phit2flit_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_enq_bits_flit (_in_phits_io_inner_ser_2_in_phit2flit_io_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_ready     (io_inner_ser_2_in_ready),
    .io_deq_valid     (io_inner_ser_2_in_valid),
    .io_deq_bits_flit (io_inner_ser_2_in_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  AsyncQueue in_phits_in_async_3 (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_enq_clock     (io_outer_clock),
    .io_enq_reset     (io_outer_reset),
    .io_enq_ready     (_in_phits_in_async_3_io_enq_ready),
    .io_enq_valid     (_in_demux_io_out_3_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_enq_bits_phit (_in_demux_io_out_3_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_deq_clock     (io_inner_clock),
    .io_deq_reset     (io_inner_reset),
    .io_deq_ready     (_in_phits_io_inner_ser_3_in_phit2flit_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_valid     (_in_phits_in_async_3_io_deq_valid),
    .io_deq_bits_phit (_in_phits_in_async_3_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  PhitToFlit in_phits_io_inner_ser_3_in_phit2flit (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_in_phits_io_inner_ser_3_in_phit2flit_io_in_ready),
    .io_in_valid      (_in_phits_in_async_3_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_in_bits_phit  (_in_phits_in_async_3_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_ready     (_in_phits_io_inner_ser_3_in_q_io_enq_ready),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_valid     (_in_phits_io_inner_ser_3_in_phit2flit_io_out_valid),
    .io_out_bits_flit (_in_phits_io_inner_ser_3_in_phit2flit_io_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  Queue_69 in_phits_io_inner_ser_3_in_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (_in_phits_io_inner_ser_3_in_q_io_enq_ready),
    .io_enq_valid     (_in_phits_io_inner_ser_3_in_phit2flit_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_enq_bits_flit (_in_phits_io_inner_ser_3_in_phit2flit_io_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_ready     (io_inner_ser_3_in_ready),
    .io_deq_valid     (io_inner_ser_3_in_valid),
    .io_deq_bits_flit (io_inner_ser_3_in_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  AsyncQueue in_phits_in_async_4 (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_enq_clock     (io_outer_clock),
    .io_enq_reset     (io_outer_reset),
    .io_enq_ready     (_in_phits_in_async_4_io_enq_ready),
    .io_enq_valid     (_in_demux_io_out_4_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_enq_bits_phit (_in_demux_io_out_4_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .io_deq_clock     (io_inner_clock),
    .io_deq_reset     (io_inner_reset),
    .io_deq_ready     (_in_phits_io_inner_ser_4_in_phit2flit_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_valid     (_in_phits_in_async_4_io_deq_valid),
    .io_deq_bits_phit (_in_phits_in_async_4_io_deq_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
  PhitToFlit in_phits_io_inner_ser_4_in_phit2flit (	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_in_ready      (_in_phits_io_inner_ser_4_in_phit2flit_io_in_ready),
    .io_in_valid      (_in_phits_in_async_4_io_deq_valid),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_in_bits_phit  (_in_phits_in_async_4_io_deq_bits_phit),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_ready     (_in_phits_io_inner_ser_4_in_q_io_enq_ready),	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .io_out_valid     (_in_phits_io_inner_ser_4_in_phit2flit_io_out_valid),
    .io_out_bits_flit (_in_phits_io_inner_ser_4_in_phit2flit_io_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
  Queue_69 in_phits_io_inner_ser_4_in_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
    .clock            (io_inner_clock),
    .reset            (io_inner_reset),
    .io_enq_ready     (_in_phits_io_inner_ser_4_in_q_io_enq_ready),
    .io_enq_valid     (_in_phits_io_inner_ser_4_in_phit2flit_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_enq_bits_flit (_in_phits_io_inner_ser_4_in_phit2flit_io_out_bits_flit),	// @[generators/testchipip/src/main/scala/serdes/Serdes.scala:123:27]
    .io_deq_ready     (io_inner_ser_4_in_ready),
    .io_deq_valid     (io_inner_ser_4_in_valid),
    .io_deq_bits_flit (io_inner_ser_4_in_bits_flit)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:376:21]
  PhitDemux in_demux (	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
    .clock              (io_outer_clock),
    .reset              (io_outer_reset),
    .io_in_ready        (_in_demux_io_in_ready),
    .io_in_valid        (io_outer_ser_in_valid),
    .io_in_bits_phit    (io_outer_ser_in_bits_phit),
    .io_out_0_ready     (_in_phits_in_async_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_0_valid     (_in_demux_io_out_0_valid),
    .io_out_0_bits_phit (_in_demux_io_out_0_bits_phit),
    .io_out_1_ready     (_in_phits_in_async_1_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_1_valid     (_in_demux_io_out_1_valid),
    .io_out_1_bits_phit (_in_demux_io_out_1_bits_phit),
    .io_out_2_ready     (_in_phits_in_async_2_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_2_valid     (_in_demux_io_out_2_valid),
    .io_out_2_bits_phit (_in_demux_io_out_2_bits_phit),
    .io_out_3_ready     (_in_phits_in_async_3_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_3_valid     (_in_demux_io_out_3_valid),
    .io_out_3_bits_phit (_in_demux_io_out_3_bits_phit),
    .io_out_4_ready     (_in_phits_in_async_4_io_enq_ready),	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:43:26]
    .io_out_4_valid     (_in_demux_io_out_4_valid),
    .io_out_4_bits_phit (_in_demux_io_out_4_bits_phit)
  );	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11]
  assign io_outer_ser_in_ready = ~io_outer_reset & _in_demux_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:54:11, :57:18, :61:25, :62:28]
  assign io_outer_ser_out_valid = ~io_outer_reset & _out_arb_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/SerialPhy.scala:37:11, :40:20, :57:18, :61:25, :62:28, :63:28]
endmodule

