// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FrontBus(
  output        auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [31:0] auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [1:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [1:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_fbus_clock_groups_in_member_fbus_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_fbus_clock_groups_in_member_fbus_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_bus_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_bus_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_bus_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_bus_xing_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_bus_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [8:0]  auto_bus_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [31:0] auto_bus_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_bus_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_bus_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_bus_xing_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_bus_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_bus_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_bus_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_bus_xing_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_bus_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [8:0]  auto_bus_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_bus_xing_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_bus_xing_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_bus_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_bus_xing_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        uart_tsi_io_uart_txd,	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:43:27]
  input         uart_tsi_io_uart_rxd,	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:43:27]
  output        uart_tsi_io_dropped,	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:43:27]
  output [3:0]  uart_tsi_io_tsi2tl_state	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:43:27]
);

  wire        _width_adapter_io_narrow_in_ready;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
  wire        _width_adapter_io_narrow_out_valid;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
  wire [7:0]  _width_adapter_io_narrow_out_bits;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
  wire        _width_adapter_io_wide_in_ready;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
  wire        _width_adapter_io_wide_out_valid;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
  wire [31:0] _width_adapter_io_wide_out_bits;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
  wire        _uart_to_serial_io_serial_in_ready;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:39:34]
  wire        _uart_to_serial_io_serial_out_valid;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:39:34]
  wire [7:0]  _uart_to_serial_io_serial_out_bits;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:39:34]
  wire        _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_param;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [7:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [31:0] _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_address;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [7:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_mask;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [63:0] _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_corrupt;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_port_named_serial_tl_0_in_auto_tl_out_d_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _tsi2tl_auto_out_a_valid;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire [2:0]  _tsi2tl_auto_out_a_bits_opcode;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire [2:0]  _tsi2tl_auto_out_a_bits_size;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire [31:0] _tsi2tl_auto_out_a_bits_address;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire [7:0]  _tsi2tl_auto_out_a_bits_mask;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire [63:0] _tsi2tl_auto_out_a_bits_data;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire        _tsi2tl_auto_out_d_ready;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire        _tsi2tl_io_tsi_in_ready;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire        _tsi2tl_io_tsi_out_valid;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire [31:0] _tsi2tl_io_tsi_out_bits;	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  wire        _buffer_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire        _buffer_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire [2:0]  _buffer_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire [1:0]  _buffer_auto_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire [2:0]  _buffer_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire [8:0]  _buffer_auto_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire [1:0]  _buffer_auto_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire        _buffer_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire [63:0] _buffer_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire        _buffer_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  wire        _fbus_xbar_auto_anon_in_1_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire        _fbus_xbar_auto_anon_in_1_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [2:0]  _fbus_xbar_auto_anon_in_1_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [1:0]  _fbus_xbar_auto_anon_in_1_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [2:0]  _fbus_xbar_auto_anon_in_1_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [7:0]  _fbus_xbar_auto_anon_in_1_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [1:0]  _fbus_xbar_auto_anon_in_1_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire        _fbus_xbar_auto_anon_in_1_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [63:0] _fbus_xbar_auto_anon_in_1_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire        _fbus_xbar_auto_anon_in_1_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire        _fbus_xbar_auto_anon_in_0_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire        _fbus_xbar_auto_anon_in_0_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [63:0] _fbus_xbar_auto_anon_in_0_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire        _fbus_xbar_auto_anon_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [2:0]  _fbus_xbar_auto_anon_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [2:0]  _fbus_xbar_auto_anon_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [2:0]  _fbus_xbar_auto_anon_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [8:0]  _fbus_xbar_auto_anon_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [31:0] _fbus_xbar_auto_anon_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [7:0]  _fbus_xbar_auto_anon_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire [63:0] _fbus_xbar_auto_anon_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire        _fbus_xbar_auto_anon_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  wire        _fbus_xbar_auto_anon_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  TLXbar_3 fbus_xbar (	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .clock                         (auto_fbus_clock_groups_in_member_fbus_0_clock),
    .reset                         (auto_fbus_clock_groups_in_member_fbus_0_reset),
    .auto_anon_in_1_a_ready        (_fbus_xbar_auto_anon_in_1_a_ready),
    .auto_anon_in_1_a_valid        (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_a_bits_opcode  (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_a_bits_param   (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_param),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_a_bits_size    (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_a_bits_source  (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_a_bits_address (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_address),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_a_bits_mask    (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_mask),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_a_bits_data    (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_data),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_a_bits_corrupt (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_corrupt),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_d_ready        (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_d_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_1_d_valid        (_fbus_xbar_auto_anon_in_1_d_valid),
    .auto_anon_in_1_d_bits_opcode  (_fbus_xbar_auto_anon_in_1_d_bits_opcode),
    .auto_anon_in_1_d_bits_param   (_fbus_xbar_auto_anon_in_1_d_bits_param),
    .auto_anon_in_1_d_bits_size    (_fbus_xbar_auto_anon_in_1_d_bits_size),
    .auto_anon_in_1_d_bits_source  (_fbus_xbar_auto_anon_in_1_d_bits_source),
    .auto_anon_in_1_d_bits_sink    (_fbus_xbar_auto_anon_in_1_d_bits_sink),
    .auto_anon_in_1_d_bits_denied  (_fbus_xbar_auto_anon_in_1_d_bits_denied),
    .auto_anon_in_1_d_bits_data    (_fbus_xbar_auto_anon_in_1_d_bits_data),
    .auto_anon_in_1_d_bits_corrupt (_fbus_xbar_auto_anon_in_1_d_bits_corrupt),
    .auto_anon_in_0_a_ready        (_fbus_xbar_auto_anon_in_0_a_ready),
    .auto_anon_in_0_a_valid        (_tsi2tl_auto_out_a_valid),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .auto_anon_in_0_a_bits_opcode  (_tsi2tl_auto_out_a_bits_opcode),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .auto_anon_in_0_a_bits_size    (_tsi2tl_auto_out_a_bits_size),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .auto_anon_in_0_a_bits_address (_tsi2tl_auto_out_a_bits_address),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .auto_anon_in_0_a_bits_mask    (_tsi2tl_auto_out_a_bits_mask),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .auto_anon_in_0_a_bits_data    (_tsi2tl_auto_out_a_bits_data),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .auto_anon_in_0_d_ready        (_tsi2tl_auto_out_d_ready),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .auto_anon_in_0_d_valid        (_fbus_xbar_auto_anon_in_0_d_valid),
    .auto_anon_in_0_d_bits_data    (_fbus_xbar_auto_anon_in_0_d_bits_data),
    .auto_anon_out_a_ready         (_buffer_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .auto_anon_out_a_valid         (_fbus_xbar_auto_anon_out_a_valid),
    .auto_anon_out_a_bits_opcode   (_fbus_xbar_auto_anon_out_a_bits_opcode),
    .auto_anon_out_a_bits_param    (_fbus_xbar_auto_anon_out_a_bits_param),
    .auto_anon_out_a_bits_size     (_fbus_xbar_auto_anon_out_a_bits_size),
    .auto_anon_out_a_bits_source   (_fbus_xbar_auto_anon_out_a_bits_source),
    .auto_anon_out_a_bits_address  (_fbus_xbar_auto_anon_out_a_bits_address),
    .auto_anon_out_a_bits_mask     (_fbus_xbar_auto_anon_out_a_bits_mask),
    .auto_anon_out_a_bits_data     (_fbus_xbar_auto_anon_out_a_bits_data),
    .auto_anon_out_a_bits_corrupt  (_fbus_xbar_auto_anon_out_a_bits_corrupt),
    .auto_anon_out_d_ready         (_fbus_xbar_auto_anon_out_d_ready),
    .auto_anon_out_d_valid         (_buffer_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .auto_anon_out_d_bits_opcode   (_buffer_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .auto_anon_out_d_bits_param    (_buffer_auto_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .auto_anon_out_d_bits_size     (_buffer_auto_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .auto_anon_out_d_bits_source   (_buffer_auto_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .auto_anon_out_d_bits_sink     (_buffer_auto_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .auto_anon_out_d_bits_denied   (_buffer_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .auto_anon_out_d_bits_data     (_buffer_auto_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .auto_anon_out_d_bits_corrupt  (_buffer_auto_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  TLBuffer_3 buffer (	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
    .clock                   (auto_fbus_clock_groups_in_member_fbus_0_clock),
    .reset                   (auto_fbus_clock_groups_in_member_fbus_0_reset),
    .auto_in_a_ready         (_buffer_auto_in_a_ready),
    .auto_in_a_valid         (_fbus_xbar_auto_anon_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_a_bits_opcode   (_fbus_xbar_auto_anon_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_a_bits_param    (_fbus_xbar_auto_anon_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_a_bits_size     (_fbus_xbar_auto_anon_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_a_bits_source   (_fbus_xbar_auto_anon_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_a_bits_address  (_fbus_xbar_auto_anon_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_a_bits_mask     (_fbus_xbar_auto_anon_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_a_bits_data     (_fbus_xbar_auto_anon_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_a_bits_corrupt  (_fbus_xbar_auto_anon_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_d_ready         (_fbus_xbar_auto_anon_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_in_d_valid         (_buffer_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_buffer_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_buffer_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_buffer_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_buffer_auto_in_d_bits_source),
    .auto_in_d_bits_sink     (_buffer_auto_in_d_bits_sink),
    .auto_in_d_bits_denied   (_buffer_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_buffer_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_buffer_auto_in_d_bits_corrupt),
    .auto_out_a_ready        (auto_bus_xing_out_a_ready),
    .auto_out_a_valid        (auto_bus_xing_out_a_valid),
    .auto_out_a_bits_opcode  (auto_bus_xing_out_a_bits_opcode),
    .auto_out_a_bits_param   (auto_bus_xing_out_a_bits_param),
    .auto_out_a_bits_size    (auto_bus_xing_out_a_bits_size),
    .auto_out_a_bits_source  (auto_bus_xing_out_a_bits_source),
    .auto_out_a_bits_address (auto_bus_xing_out_a_bits_address),
    .auto_out_a_bits_mask    (auto_bus_xing_out_a_bits_mask),
    .auto_out_a_bits_data    (auto_bus_xing_out_a_bits_data),
    .auto_out_a_bits_corrupt (auto_bus_xing_out_a_bits_corrupt),
    .auto_out_d_ready        (auto_bus_xing_out_d_ready),
    .auto_out_d_valid        (auto_bus_xing_out_d_valid),
    .auto_out_d_bits_opcode  (auto_bus_xing_out_d_bits_opcode),
    .auto_out_d_bits_param   (auto_bus_xing_out_d_bits_param),
    .auto_out_d_bits_size    (auto_bus_xing_out_d_bits_size),
    .auto_out_d_bits_source  (auto_bus_xing_out_d_bits_source),
    .auto_out_d_bits_sink    (auto_bus_xing_out_d_bits_sink),
    .auto_out_d_bits_denied  (auto_bus_xing_out_d_bits_denied),
    .auto_out_d_bits_data    (auto_bus_xing_out_d_bits_data),
    .auto_out_d_bits_corrupt (auto_bus_xing_out_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:73:28]
  TSIToTileLink tsi2tl (	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .clock                   (auto_fbus_clock_groups_in_member_fbus_0_clock),
    .reset                   (auto_fbus_clock_groups_in_member_fbus_0_reset),
    .auto_out_a_ready        (_fbus_xbar_auto_anon_in_0_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_out_a_valid        (_tsi2tl_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_tsi2tl_auto_out_a_bits_opcode),
    .auto_out_a_bits_size    (_tsi2tl_auto_out_a_bits_size),
    .auto_out_a_bits_address (_tsi2tl_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_tsi2tl_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_tsi2tl_auto_out_a_bits_data),
    .auto_out_d_ready        (_tsi2tl_auto_out_d_ready),
    .auto_out_d_valid        (_fbus_xbar_auto_anon_in_0_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_out_d_bits_data    (_fbus_xbar_auto_anon_in_0_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .io_tsi_in_ready         (_tsi2tl_io_tsi_in_ready),
    .io_tsi_in_valid         (_width_adapter_io_wide_out_valid),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
    .io_tsi_in_bits          (_width_adapter_io_wide_out_bits),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
    .io_tsi_out_ready        (_width_adapter_io_wide_in_ready),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
    .io_tsi_out_valid        (_tsi2tl_io_tsi_out_valid),
    .io_tsi_out_bits         (_tsi2tl_io_tsi_out_bits),
    .io_state                (uart_tsi_io_tsi2tl_state)
  );	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
  TLInterconnectCoupler_5 coupler_from_port_named_serial_tl_0_in (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                         (auto_fbus_clock_groups_in_member_fbus_0_clock),
    .reset                         (auto_fbus_clock_groups_in_member_fbus_0_reset),
    .auto_buffer_in_a_ready        (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_ready),
    .auto_buffer_in_a_valid        (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_valid),
    .auto_buffer_in_a_bits_opcode  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_opcode),
    .auto_buffer_in_a_bits_param   (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_param),
    .auto_buffer_in_a_bits_size    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_size),
    .auto_buffer_in_a_bits_source  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_source),
    .auto_buffer_in_a_bits_address (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_address),
    .auto_buffer_in_a_bits_mask    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_mask),
    .auto_buffer_in_a_bits_data    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_data),
    .auto_buffer_in_a_bits_corrupt (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_corrupt),
    .auto_buffer_in_d_ready        (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_ready),
    .auto_buffer_in_d_valid        (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_valid),
    .auto_buffer_in_d_bits_opcode  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_opcode),
    .auto_buffer_in_d_bits_param   (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_param),
    .auto_buffer_in_d_bits_size    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_size),
    .auto_buffer_in_d_bits_source  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_source),
    .auto_buffer_in_d_bits_sink    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_sink),
    .auto_buffer_in_d_bits_denied  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_denied),
    .auto_buffer_in_d_bits_data    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_data),
    .auto_buffer_in_d_bits_corrupt (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_corrupt),
    .auto_tl_out_a_ready           (_fbus_xbar_auto_anon_in_1_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_tl_out_a_valid           (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_valid),
    .auto_tl_out_a_bits_opcode     (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_opcode),
    .auto_tl_out_a_bits_param      (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_param),
    .auto_tl_out_a_bits_size       (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_size),
    .auto_tl_out_a_bits_source     (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_source),
    .auto_tl_out_a_bits_address    (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_address),
    .auto_tl_out_a_bits_mask       (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_mask),
    .auto_tl_out_a_bits_data       (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_data),
    .auto_tl_out_a_bits_corrupt    (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_corrupt),
    .auto_tl_out_d_ready           (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_d_ready),
    .auto_tl_out_d_valid           (_fbus_xbar_auto_anon_in_1_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_tl_out_d_bits_opcode     (_fbus_xbar_auto_anon_in_1_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_tl_out_d_bits_param      (_fbus_xbar_auto_anon_in_1_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_tl_out_d_bits_size       (_fbus_xbar_auto_anon_in_1_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_tl_out_d_bits_source     (_fbus_xbar_auto_anon_in_1_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_tl_out_d_bits_sink       (_fbus_xbar_auto_anon_in_1_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_tl_out_d_bits_denied     (_fbus_xbar_auto_anon_in_1_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_tl_out_d_bits_data       (_fbus_xbar_auto_anon_in_1_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
    .auto_tl_out_d_bits_corrupt    (_fbus_xbar_auto_anon_in_1_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:239:32]
  );	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  UARTToSerial uart_to_serial (	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:39:34]
    .clock               (auto_fbus_clock_groups_in_member_fbus_0_clock),
    .reset               (auto_fbus_clock_groups_in_member_fbus_0_reset),
    .io_uart_txd         (uart_tsi_io_uart_txd),
    .io_uart_rxd         (uart_tsi_io_uart_rxd),
    .io_serial_in_ready  (_uart_to_serial_io_serial_in_ready),
    .io_serial_in_valid  (_width_adapter_io_narrow_out_valid),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
    .io_serial_in_bits   (_width_adapter_io_narrow_out_bits),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
    .io_serial_out_ready (_width_adapter_io_narrow_in_ready),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
    .io_serial_out_valid (_uart_to_serial_io_serial_out_valid),
    .io_serial_out_bits  (_uart_to_serial_io_serial_out_bits),
    .io_dropped          (uart_tsi_io_dropped)
  );	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:39:34]
  SerialWidthAdapter width_adapter (	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
    .clock               (auto_fbus_clock_groups_in_member_fbus_0_clock),
    .reset               (auto_fbus_clock_groups_in_member_fbus_0_reset),
    .io_narrow_in_ready  (_width_adapter_io_narrow_in_ready),
    .io_narrow_in_valid  (_uart_to_serial_io_serial_out_valid),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:39:34]
    .io_narrow_in_bits   (_uart_to_serial_io_serial_out_bits),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:39:34]
    .io_narrow_out_ready (_uart_to_serial_io_serial_in_ready),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:39:34]
    .io_narrow_out_valid (_width_adapter_io_narrow_out_valid),
    .io_narrow_out_bits  (_width_adapter_io_narrow_out_bits),
    .io_wide_in_ready    (_width_adapter_io_wide_in_ready),
    .io_wide_in_valid    (_tsi2tl_io_tsi_out_valid),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .io_wide_in_bits     (_tsi2tl_io_tsi_out_bits),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .io_wide_out_ready   (_tsi2tl_io_tsi_in_ready),	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:36:36]
    .io_wide_out_valid   (_width_adapter_io_wide_out_valid),
    .io_wide_out_bits    (_width_adapter_io_wide_out_bits)
  );	// @[generators/testchipip/src/main/scala/tsi/PeripheryUARTTSI.scala:40:33]
endmodule

