// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module SystemBus(
  input         auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [8:0]  auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [30:0] auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [8:0]  auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_to_bus_named_coh_widget_anon_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_to_bus_named_coh_widget_anon_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [8:0]  auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [31:0] auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_to_bus_named_coh_widget_anon_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_to_bus_named_coh_widget_anon_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [8:0]  auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_from_bus_named_fbus_bus_xing_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [8:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [31:0] auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_from_bus_named_fbus_bus_xing_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [1:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [8:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [1:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_sbus_clock_groups_in_member_sbus_2_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_sbus_clock_groups_in_member_sbus_2_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_sbus_clock_groups_in_member_sbus_1_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_sbus_clock_groups_in_member_sbus_1_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_sbus_clock_groups_in_member_sbus_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_sbus_clock_groups_in_member_sbus_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_sbus_clock_groups_out_1_member_subsystem_obus_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_sbus_clock_groups_out_1_member_subsystem_obus_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_sbus_clock_groups_out_0_member_coh_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_sbus_clock_groups_out_0_member_coh_0_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
);

  wire _fixedClockNode_auto_anon_out_0_clock;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:114:114]
  wire _fixedClockNode_auto_anon_out_0_reset;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:114:114]
  FixedClockBroadcast fixedClockNode (	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:114:114]
    .auto_anon_in_clock    (auto_sbus_clock_groups_in_member_sbus_0_clock),
    .auto_anon_in_reset    (auto_sbus_clock_groups_in_member_sbus_0_reset),
    .auto_anon_out_0_clock (_fixedClockNode_auto_anon_out_0_clock),
    .auto_anon_out_0_reset (_fixedClockNode_auto_anon_out_0_reset)
  );	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:114:114]
  TLXbar system_bus_xbar (	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .clock                          (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:114:114]
    .reset                          (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:114:114]
    .auto_anon_in_a_ready           (auto_coupler_from_bus_named_fbus_bus_xing_in_a_ready),
    .auto_anon_in_a_valid           (auto_coupler_from_bus_named_fbus_bus_xing_in_a_valid),
    .auto_anon_in_a_bits_opcode     (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_opcode),
    .auto_anon_in_a_bits_param      (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_param),
    .auto_anon_in_a_bits_size       (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_size),
    .auto_anon_in_a_bits_source     (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_source),
    .auto_anon_in_a_bits_address    (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_address),
    .auto_anon_in_a_bits_mask       (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_mask),
    .auto_anon_in_a_bits_data       (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_data),
    .auto_anon_in_a_bits_corrupt    (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_corrupt),
    .auto_anon_in_d_ready           (auto_coupler_from_bus_named_fbus_bus_xing_in_d_ready),
    .auto_anon_in_d_valid           (auto_coupler_from_bus_named_fbus_bus_xing_in_d_valid),
    .auto_anon_in_d_bits_opcode     (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_opcode),
    .auto_anon_in_d_bits_param      (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_param),
    .auto_anon_in_d_bits_size       (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_size),
    .auto_anon_in_d_bits_source     (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_source),
    .auto_anon_in_d_bits_sink       (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_sink),
    .auto_anon_in_d_bits_denied     (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_denied),
    .auto_anon_in_d_bits_data       (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_data),
    .auto_anon_in_d_bits_corrupt    (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_corrupt),
    .auto_anon_out_1_a_ready        (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_ready),
    .auto_anon_out_1_a_valid        (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_valid),
    .auto_anon_out_1_a_bits_opcode  (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_opcode),
    .auto_anon_out_1_a_bits_param   (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_param),
    .auto_anon_out_1_a_bits_size    (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_size),
    .auto_anon_out_1_a_bits_source  (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_source),
    .auto_anon_out_1_a_bits_address (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_address),
    .auto_anon_out_1_a_bits_mask    (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_mask),
    .auto_anon_out_1_a_bits_data    (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_data),
    .auto_anon_out_1_a_bits_corrupt (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_a_bits_corrupt),
    .auto_anon_out_1_d_ready        (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_ready),
    .auto_anon_out_1_d_valid        (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_valid),
    .auto_anon_out_1_d_bits_opcode  (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_opcode),
    .auto_anon_out_1_d_bits_param   (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_param),
    .auto_anon_out_1_d_bits_size    (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_size),
    .auto_anon_out_1_d_bits_source  (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_source),
    .auto_anon_out_1_d_bits_sink    (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_sink),
    .auto_anon_out_1_d_bits_denied  (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_denied),
    .auto_anon_out_1_d_bits_data    (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_data),
    .auto_anon_out_1_d_bits_corrupt (auto_coupler_to_bus_named_subsystem_obus_widget_anon_out_d_bits_corrupt),
    .auto_anon_out_0_a_ready        (auto_coupler_to_bus_named_coh_widget_anon_out_a_ready),
    .auto_anon_out_0_a_valid        (auto_coupler_to_bus_named_coh_widget_anon_out_a_valid),
    .auto_anon_out_0_a_bits_opcode  (auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_opcode),
    .auto_anon_out_0_a_bits_param   (auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_param),
    .auto_anon_out_0_a_bits_size    (auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_size),
    .auto_anon_out_0_a_bits_source  (auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_source),
    .auto_anon_out_0_a_bits_address (auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_address),
    .auto_anon_out_0_a_bits_mask    (auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_mask),
    .auto_anon_out_0_a_bits_data    (auto_coupler_to_bus_named_coh_widget_anon_out_a_bits_data),
    .auto_anon_out_0_d_ready        (auto_coupler_to_bus_named_coh_widget_anon_out_d_ready),
    .auto_anon_out_0_d_valid        (auto_coupler_to_bus_named_coh_widget_anon_out_d_valid),
    .auto_anon_out_0_d_bits_opcode  (auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_opcode),
    .auto_anon_out_0_d_bits_param   (auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_param),
    .auto_anon_out_0_d_bits_size    (auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_size),
    .auto_anon_out_0_d_bits_source  (auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_source),
    .auto_anon_out_0_d_bits_sink    (auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_sink),
    .auto_anon_out_0_d_bits_denied  (auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_denied),
    .auto_anon_out_0_d_bits_data    (auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_data),
    .auto_anon_out_0_d_bits_corrupt (auto_coupler_to_bus_named_coh_widget_anon_out_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  assign auto_sbus_clock_groups_out_1_member_subsystem_obus_0_clock = auto_sbus_clock_groups_in_member_sbus_2_clock;
  assign auto_sbus_clock_groups_out_1_member_subsystem_obus_0_reset = auto_sbus_clock_groups_in_member_sbus_2_reset;
  assign auto_sbus_clock_groups_out_0_member_coh_0_clock = auto_sbus_clock_groups_in_member_sbus_1_clock;
  assign auto_sbus_clock_groups_out_0_member_coh_0_reset = auto_sbus_clock_groups_in_member_sbus_1_reset;
endmodule

