// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLDToBeat(
  input         clock,
  input         reset,
  output        io_protocol_ready,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input         io_protocol_valid,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input  [2:0]  io_protocol_bits_opcode,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input  [1:0]  io_protocol_bits_param,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input  [7:0]  io_protocol_bits_size,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input  [7:0]  io_protocol_bits_source,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input  [7:0]  io_protocol_bits_sink,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input         io_protocol_bits_denied,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input  [63:0] io_protocol_bits_data,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input         io_protocol_bits_corrupt,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  input         io_beat_ready,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  output        io_beat_valid,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  output [64:0] io_beat_bits_payload,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  output        io_beat_bits_head,	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
  output        io_beat_bits_tail	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:39:14]
);

  wire         _q_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  wire [2:0]   _q_io_deq_bits_opcode;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  wire [1:0]   _q_io_deq_bits_param;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  wire [7:0]   _q_io_deq_bits_size;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  wire [7:0]   _q_io_deq_bits_source;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  wire [7:0]   _q_io_deq_bits_sink;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  wire         _q_io_deq_bits_denied;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  wire [63:0]  _q_io_deq_bits_data;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  wire         _q_io_deq_bits_corrupt;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  wire [260:0] _GEN = {253'h0, _q_io_deq_bits_size};	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  reg  [2:0]   head_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire         head = head_counter == 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  wire [260:0] _tail_beats1_decode_T_1 = 261'h3F << _GEN;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [2:0]   tail_beats1 = _q_io_deq_bits_opcode[0] ? ~(_tail_beats1_decode_T_1[5:3]) : 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  reg  [2:0]   tail_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  reg          is_body;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:59:24]
  wire         q_io_deq_ready = io_beat_ready & (is_body | ~(_q_io_deq_bits_opcode[0]));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17, :59:24, :61:{35,47,50}]
  wire         io_beat_bits_head_0 = head & ~is_body;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:59:24, :63:{35,38}]
  wire         io_beat_bits_tail_0 = (tail_counter == 3'h1 | tail_beats1 == 3'h0) & (is_body | ~(_q_io_deq_bits_opcode[0]));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, :229:27, :232:{25,33,43}, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17, :59:24, :61:50, :64:{35,47}]
  wire [260:0] _head_beats1_decode_T_1 = 261'h3F << _GEN;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire         _GEN_0 = io_beat_ready & _q_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  always @(posedge clock) begin
    if (reset) begin
      head_counter <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      tail_counter <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      is_body <= 1'h0;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:59:24]
    end
    else begin
      if (q_io_deq_ready & _q_io_deq_valid) begin	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17, :61:35, src/main/scala/chisel3/util/Decoupled.scala:52:35]
        if (head)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25]
          head_counter <= _q_io_deq_bits_opcode[0] ? ~(_head_beats1_decode_T_1[5:3]) : 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, :229:27, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25]
          head_counter <= head_counter - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28]
        if (tail_counter == 3'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
          tail_counter <= tail_beats1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25]
          tail_counter <= tail_counter - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28]
      end
      is_body <= ~(_GEN_0 & io_beat_bits_tail_0) & (_GEN_0 & io_beat_bits_head_0 | is_body);	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:59:24, :63:35, :64:35, :67:{22,44,54}, :68:{22,44,54}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        head_counter = _RANDOM[/*Zero width*/ 1'b0][2:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
        tail_counter = _RANDOM[/*Zero width*/ 1'b0][5:3];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
        is_body = _RANDOM[/*Zero width*/ 1'b0][6];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:59:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue_65 q (	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (io_protocol_ready),
    .io_enq_valid        (io_protocol_valid),
    .io_enq_bits_opcode  (io_protocol_bits_opcode),
    .io_enq_bits_param   (io_protocol_bits_param),
    .io_enq_bits_size    (io_protocol_bits_size),
    .io_enq_bits_source  (io_protocol_bits_source),
    .io_enq_bits_sink    (io_protocol_bits_sink),
    .io_enq_bits_denied  (io_protocol_bits_denied),
    .io_enq_bits_data    (io_protocol_bits_data),
    .io_enq_bits_corrupt (io_protocol_bits_corrupt),
    .io_deq_ready        (q_io_deq_ready),	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:61:35]
    .io_deq_valid        (_q_io_deq_valid),
    .io_deq_bits_opcode  (_q_io_deq_bits_opcode),
    .io_deq_bits_param   (_q_io_deq_bits_param),
    .io_deq_bits_size    (_q_io_deq_bits_size),
    .io_deq_bits_source  (_q_io_deq_bits_source),
    .io_deq_bits_sink    (_q_io_deq_bits_sink),
    .io_deq_bits_denied  (_q_io_deq_bits_denied),
    .io_deq_bits_data    (_q_io_deq_bits_data),
    .io_deq_bits_corrupt (_q_io_deq_bits_corrupt)
  );	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  assign io_beat_valid = _q_io_deq_valid;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17]
  assign io_beat_bits_payload = is_body ? {_q_io_deq_bits_data, _q_io_deq_bits_corrupt} : {35'h0, _q_io_deq_bits_opcode, _q_io_deq_bits_param, _q_io_deq_bits_size, _q_io_deq_bits_source, _q_io_deq_bits_sink, _q_io_deq_bits_denied};	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:46:17, :56:18, :59:24, :65:33]
  assign io_beat_bits_head = io_beat_bits_head_0;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:63:35]
  assign io_beat_bits_tail = io_beat_bits_tail_0;	// @[generators/testchipip/src/main/scala/serdes/TLChannelCompactor.scala:64:35]
endmodule

