// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLInterconnectCoupler_9(
  input         clock,
  input         reset,
  input         auto_blocker_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_blocker_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_blocker_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_blocker_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_blocker_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_blocker_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [30:0] auto_blocker_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_blocker_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_blocker_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_blocker_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_blocker_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_blocker_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_blocker_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_blocker_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_blocker_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_blocker_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_blocker_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_blocker_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_blocker_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_blocker_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_tl_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_tl_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_tl_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_tl_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_tl_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [8:0]  auto_tl_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [30:0] auto_tl_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_tl_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_tl_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_tl_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_tl_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_tl_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_tl_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [1:0]  auto_tl_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_tl_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [8:0]  auto_tl_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_tl_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_tl_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_tl_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_tl_in_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
);

  wire        _combiner_auto_out_a_valid;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire [2:0]  _combiner_auto_out_a_bits_opcode;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire [2:0]  _combiner_auto_out_a_bits_param;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire [2:0]  _combiner_auto_out_a_bits_size;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire [9:0]  _combiner_auto_out_a_bits_source;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire [30:0] _combiner_auto_out_a_bits_address;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire [7:0]  _combiner_auto_out_a_bits_mask;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire [63:0] _combiner_auto_out_a_bits_data;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire        _combiner_auto_out_a_bits_corrupt;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire        _combiner_auto_out_d_ready;	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
  wire        _adjuster_auto_in_a_ready;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire        _adjuster_auto_in_d_valid;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [2:0]  _adjuster_auto_in_d_bits_opcode;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [1:0]  _adjuster_auto_in_d_bits_param;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [2:0]  _adjuster_auto_in_d_bits_size;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [9:0]  _adjuster_auto_in_d_bits_source;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire        _adjuster_auto_in_d_bits_sink;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire        _adjuster_auto_in_d_bits_denied;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [63:0] _adjuster_auto_in_d_bits_data;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire        _adjuster_auto_in_d_bits_corrupt;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire        _adjuster_auto_out_a_valid;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [2:0]  _adjuster_auto_out_a_bits_opcode;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [2:0]  _adjuster_auto_out_a_bits_param;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [2:0]  _adjuster_auto_out_a_bits_size;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [7:0]  _adjuster_auto_out_a_bits_source;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [30:0] _adjuster_auto_out_a_bits_address;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [7:0]  _adjuster_auto_out_a_bits_mask;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire [63:0] _adjuster_auto_out_a_bits_data;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire        _adjuster_auto_out_a_bits_corrupt;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire        _adjuster_auto_out_d_ready;	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  wire        _blocker_auto_in_a_ready;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  wire        _blocker_auto_in_d_valid;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  wire [2:0]  _blocker_auto_in_d_bits_opcode;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  wire [1:0]  _blocker_auto_in_d_bits_param;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  wire [2:0]  _blocker_auto_in_d_bits_size;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  wire [7:0]  _blocker_auto_in_d_bits_source;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  wire        _blocker_auto_in_d_bits_sink;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  wire        _blocker_auto_in_d_bits_denied;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  wire [63:0] _blocker_auto_in_d_bits_data;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  wire        _blocker_auto_in_d_bits_corrupt;	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  TLProbeBlocker blocker (	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_in_a_ready         (_blocker_auto_in_a_ready),
    .auto_in_a_valid         (_adjuster_auto_out_a_valid),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_a_bits_opcode   (_adjuster_auto_out_a_bits_opcode),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_a_bits_param    (_adjuster_auto_out_a_bits_param),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_a_bits_size     (_adjuster_auto_out_a_bits_size),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_a_bits_source   (_adjuster_auto_out_a_bits_source),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_a_bits_address  (_adjuster_auto_out_a_bits_address),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_a_bits_mask     (_adjuster_auto_out_a_bits_mask),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_a_bits_data     (_adjuster_auto_out_a_bits_data),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_a_bits_corrupt  (_adjuster_auto_out_a_bits_corrupt),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_d_ready         (_adjuster_auto_out_d_ready),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_d_valid         (_blocker_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_blocker_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_blocker_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_blocker_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_blocker_auto_in_d_bits_source),
    .auto_in_d_bits_sink     (_blocker_auto_in_d_bits_sink),
    .auto_in_d_bits_denied   (_blocker_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_blocker_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_blocker_auto_in_d_bits_corrupt),
    .auto_out_a_ready        (auto_blocker_out_a_ready),
    .auto_out_a_valid        (auto_blocker_out_a_valid),
    .auto_out_a_bits_opcode  (auto_blocker_out_a_bits_opcode),
    .auto_out_a_bits_param   (auto_blocker_out_a_bits_param),
    .auto_out_a_bits_size    (auto_blocker_out_a_bits_size),
    .auto_out_a_bits_source  (auto_blocker_out_a_bits_source),
    .auto_out_a_bits_address (auto_blocker_out_a_bits_address),
    .auto_out_a_bits_mask    (auto_blocker_out_a_bits_mask),
    .auto_out_a_bits_data    (auto_blocker_out_a_bits_data),
    .auto_out_a_bits_corrupt (auto_blocker_out_a_bits_corrupt),
    .auto_out_d_ready        (auto_blocker_out_d_ready),
    .auto_out_d_valid        (auto_blocker_out_d_valid),
    .auto_out_d_bits_opcode  (auto_blocker_out_d_bits_opcode),
    .auto_out_d_bits_param   (auto_blocker_out_d_bits_param),
    .auto_out_d_bits_size    (auto_blocker_out_d_bits_size),
    .auto_out_d_bits_source  (auto_blocker_out_d_bits_source),
    .auto_out_d_bits_sink    (auto_blocker_out_d_bits_sink),
    .auto_out_d_bits_denied  (auto_blocker_out_d_bits_denied),
    .auto_out_d_bits_data    (auto_blocker_out_d_bits_data),
    .auto_out_d_bits_corrupt (auto_blocker_out_d_bits_corrupt)
  );	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  TLSourceAdjuster adjuster (	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_in_a_ready         (_adjuster_auto_in_a_ready),
    .auto_in_a_valid         (_combiner_auto_out_a_valid),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_a_bits_opcode   (_combiner_auto_out_a_bits_opcode),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_a_bits_param    (_combiner_auto_out_a_bits_param),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_a_bits_size     (_combiner_auto_out_a_bits_size),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_a_bits_source   (_combiner_auto_out_a_bits_source),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_a_bits_address  (_combiner_auto_out_a_bits_address),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_a_bits_mask     (_combiner_auto_out_a_bits_mask),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_a_bits_data     (_combiner_auto_out_a_bits_data),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_a_bits_corrupt  (_combiner_auto_out_a_bits_corrupt),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_d_ready         (_combiner_auto_out_d_ready),	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .auto_in_d_valid         (_adjuster_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_adjuster_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_adjuster_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_adjuster_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_adjuster_auto_in_d_bits_source),
    .auto_in_d_bits_sink     (_adjuster_auto_in_d_bits_sink),
    .auto_in_d_bits_denied   (_adjuster_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_adjuster_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_adjuster_auto_in_d_bits_corrupt),
    .auto_out_a_ready        (_blocker_auto_in_a_ready),	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_out_a_valid        (_adjuster_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_adjuster_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_adjuster_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_adjuster_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_adjuster_auto_out_a_bits_source),
    .auto_out_a_bits_address (_adjuster_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_adjuster_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_adjuster_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt (_adjuster_auto_out_a_bits_corrupt),
    .auto_out_d_ready        (_adjuster_auto_out_d_ready),
    .auto_out_d_valid        (_blocker_auto_in_d_valid),	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_out_d_bits_opcode  (_blocker_auto_in_d_bits_opcode),	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_out_d_bits_param   (_blocker_auto_in_d_bits_param),	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_out_d_bits_size    (_blocker_auto_in_d_bits_size),	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_out_d_bits_source  (_blocker_auto_in_d_bits_source),	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_out_d_bits_sink    (_blocker_auto_in_d_bits_sink),	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_out_d_bits_denied  (_blocker_auto_in_d_bits_denied),	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_out_d_bits_data    (_blocker_auto_in_d_bits_data),	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
    .auto_out_d_bits_corrupt (_blocker_auto_in_d_bits_corrupt)	// @[generators/testchipip/src/main/scala/serdes/ProbeBlocker.scala:62:29]
  );	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  TLSourceCombiner combiner (	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
    .clock                   (clock),
    .reset                   (reset),
    .auto_in_a_ready         (auto_tl_in_a_ready),
    .auto_in_a_valid         (auto_tl_in_a_valid),
    .auto_in_a_bits_opcode   (auto_tl_in_a_bits_opcode),
    .auto_in_a_bits_param    (auto_tl_in_a_bits_param),
    .auto_in_a_bits_size     (auto_tl_in_a_bits_size),
    .auto_in_a_bits_source   (auto_tl_in_a_bits_source),
    .auto_in_a_bits_address  (auto_tl_in_a_bits_address),
    .auto_in_a_bits_mask     (auto_tl_in_a_bits_mask),
    .auto_in_a_bits_data     (auto_tl_in_a_bits_data),
    .auto_in_a_bits_corrupt  (auto_tl_in_a_bits_corrupt),
    .auto_in_d_ready         (auto_tl_in_d_ready),
    .auto_in_d_valid         (auto_tl_in_d_valid),
    .auto_in_d_bits_opcode   (auto_tl_in_d_bits_opcode),
    .auto_in_d_bits_param    (auto_tl_in_d_bits_param),
    .auto_in_d_bits_size     (auto_tl_in_d_bits_size),
    .auto_in_d_bits_source   (auto_tl_in_d_bits_source),
    .auto_in_d_bits_sink     (auto_tl_in_d_bits_sink),
    .auto_in_d_bits_denied   (auto_tl_in_d_bits_denied),
    .auto_in_d_bits_data     (auto_tl_in_d_bits_data),
    .auto_in_d_bits_corrupt  (auto_tl_in_d_bits_corrupt),
    .auto_out_a_ready        (_adjuster_auto_in_a_ready),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_out_a_valid        (_combiner_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_combiner_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_combiner_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_combiner_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_combiner_auto_out_a_bits_source),
    .auto_out_a_bits_address (_combiner_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_combiner_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_combiner_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt (_combiner_auto_out_a_bits_corrupt),
    .auto_out_d_ready        (_combiner_auto_out_d_ready),
    .auto_out_d_valid        (_adjuster_auto_in_d_valid),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_out_d_bits_opcode  (_adjuster_auto_in_d_bits_opcode),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_out_d_bits_param   (_adjuster_auto_in_d_bits_param),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_out_d_bits_size    (_adjuster_auto_in_d_bits_size),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_out_d_bits_source  (_adjuster_auto_in_d_bits_source),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_out_d_bits_sink    (_adjuster_auto_in_d_bits_sink),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_out_d_bits_denied  (_adjuster_auto_in_d_bits_denied),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_out_d_bits_data    (_adjuster_auto_in_d_bits_data),	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
    .auto_out_d_bits_corrupt (_adjuster_auto_in_d_bits_corrupt)	// @[generators/testchipip/src/main/scala/serdes/SourceAdjuster.scala:75:30]
  );	// @[generators/testchipip/src/main/scala/serdes/SourceCombiner.scala:86:30]
endmodule

