// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLSerdesser(
  input         clock,
  input         reset,
  output        auto_manager_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_manager_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_manager_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_manager_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_manager_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_manager_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [30:0] auto_manager_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_manager_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_manager_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_manager_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_manager_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_manager_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_manager_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [1:0]  auto_manager_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_manager_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_manager_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_manager_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_manager_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_manager_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_manager_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_client_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_client_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_client_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_client_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [2:0]  auto_client_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_client_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [31:0] auto_client_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [7:0]  auto_client_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output [63:0] auto_client_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_client_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        auto_client_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_client_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_client_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_client_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [2:0]  auto_client_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [7:0]  auto_client_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [1:0]  auto_client_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_client_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input  [63:0] auto_client_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  input         auto_client_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:100:25]
  output        io_ser_0_in_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input         io_ser_0_in_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input  [15:0] io_ser_0_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output [15:0] io_ser_0_out_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output        io_ser_1_in_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input         io_ser_1_in_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input  [15:0] io_ser_1_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input         io_ser_1_out_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output        io_ser_1_out_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output [15:0] io_ser_1_out_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output        io_ser_2_in_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input         io_ser_2_in_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input  [15:0] io_ser_2_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input         io_ser_2_out_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output        io_ser_2_out_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output [15:0] io_ser_2_out_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output        io_ser_3_in_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input         io_ser_3_in_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input  [15:0] io_ser_3_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input         io_ser_3_out_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output        io_ser_3_out_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output [15:0] io_ser_3_out_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output        io_ser_4_in_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input         io_ser_4_in_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input  [15:0] io_ser_4_in_bits_flit,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  input         io_ser_4_out_ready,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output        io_ser_4_out_valid,	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
  output [15:0] io_ser_4_out_bits_flit	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16]
);

  wire        _des_4_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire [85:0] _des_4_io_out_bits_payload;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_4_io_out_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_4_io_out_bits_tail;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_3_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_3_io_out_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_3_io_out_bits_tail;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_2_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_2_io_out_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_2_io_out_bits_tail;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_1_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire [64:0] _des_1_io_out_bits_payload;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_1_io_out_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_1_io_out_bits_tail;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_0_io_out_valid;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_0_io_out_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire        _des_0_io_out_bits_tail;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  wire [7:0]  _TLAFromBeat_io_protocol_bits_size;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:78:28]
  wire [63:0] _TLAFromBeat_io_protocol_bits_address;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:78:28]
  wire        _TLAFromBeat_io_beat_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:78:28]
  wire        _TLBFromBeat_io_beat_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:77:28]
  wire        _TLCFromBeat_io_beat_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:76:28]
  wire [7:0]  _TLDFromBeat_io_protocol_bits_size;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:75:28]
  wire [7:0]  _TLDFromBeat_io_protocol_bits_sink;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:75:28]
  wire        _TLDFromBeat_io_beat_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:75:28]
  wire        _TLEFromBeat_io_beat_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:74:28]
  wire        _ser_4_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
  wire        _ser_1_io_in_ready;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
  wire        _TLAToBeat_io_beat_valid;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
  wire [85:0] _TLAToBeat_io_beat_bits_payload;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
  wire        _TLAToBeat_io_beat_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
  wire        _TLAToBeat_io_beat_bits_tail;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
  wire        _TLBToBeat_io_beat_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:58:50]
  wire        _TLBToBeat_io_beat_bits_tail;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:58:50]
  wire        _TLCToBeat_io_beat_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:57:50]
  wire        _TLDToBeat_io_beat_valid;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
  wire [64:0] _TLDToBeat_io_beat_bits_payload;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
  wire        _TLDToBeat_io_beat_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
  wire        _TLDToBeat_io_beat_bits_tail;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
  wire        _TLEToBeat_io_beat_bits_head;	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:55:50]
  TLEToBeat TLEToBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:55:50]
    .clock             (clock),
    .reset             (reset),
    .io_beat_bits_head (_TLEToBeat_io_beat_bits_head)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:55:50]
  TLDToBeat TLDToBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
    .clock                    (clock),
    .reset                    (reset),
    .io_protocol_ready        (auto_client_out_d_ready),
    .io_protocol_valid        (auto_client_out_d_valid),
    .io_protocol_bits_opcode  (auto_client_out_d_bits_opcode),
    .io_protocol_bits_param   (auto_client_out_d_bits_param),
    .io_protocol_bits_size    ({5'h0, auto_client_out_d_bits_size}),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:64:21]
    .io_protocol_bits_source  (auto_client_out_d_bits_source),
    .io_protocol_bits_sink    ({6'h0, auto_client_out_d_bits_sink}),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:64:21]
    .io_protocol_bits_denied  (auto_client_out_d_bits_denied),
    .io_protocol_bits_data    (auto_client_out_d_bits_data),
    .io_protocol_bits_corrupt (auto_client_out_d_bits_corrupt),
    .io_beat_ready            (_ser_1_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
    .io_beat_valid            (_TLDToBeat_io_beat_valid),
    .io_beat_bits_payload     (_TLDToBeat_io_beat_bits_payload),
    .io_beat_bits_head        (_TLDToBeat_io_beat_bits_head),
    .io_beat_bits_tail        (_TLDToBeat_io_beat_bits_tail)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
  TLCToBeat TLCToBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:57:50]
    .clock             (clock),
    .reset             (reset),
    .io_beat_bits_head (_TLCToBeat_io_beat_bits_head)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:57:50]
  TLBToBeat TLBToBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:58:50]
    .clock             (clock),
    .reset             (reset),
    .io_beat_bits_head (_TLBToBeat_io_beat_bits_head),
    .io_beat_bits_tail (_TLBToBeat_io_beat_bits_tail)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:58:50]
  TLAToBeat TLAToBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
    .clock                    (clock),
    .reset                    (reset),
    .io_protocol_ready        (auto_manager_in_a_ready),
    .io_protocol_valid        (auto_manager_in_a_valid),
    .io_protocol_bits_opcode  (auto_manager_in_a_bits_opcode),
    .io_protocol_bits_param   (auto_manager_in_a_bits_param),
    .io_protocol_bits_size    ({5'h0, auto_manager_in_a_bits_size}),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:64:21]
    .io_protocol_bits_source  (auto_manager_in_a_bits_source),
    .io_protocol_bits_address ({33'h0, auto_manager_in_a_bits_address}),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:64:21]
    .io_protocol_bits_mask    (auto_manager_in_a_bits_mask),
    .io_protocol_bits_data    (auto_manager_in_a_bits_data),
    .io_protocol_bits_corrupt (auto_manager_in_a_bits_corrupt),
    .io_beat_ready            (_ser_4_io_in_ready),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
    .io_beat_valid            (_TLAToBeat_io_beat_valid),
    .io_beat_bits_payload     (_TLAToBeat_io_beat_bits_payload),
    .io_beat_bits_head        (_TLAToBeat_io_beat_bits_head),
    .io_beat_bits_tail        (_TLAToBeat_io_beat_bits_tail)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
  GenericSerializer ser_0 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
    .io_in_bits_head  (_TLEToBeat_io_beat_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:55:50]
    .io_out_bits_flit (io_ser_0_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
  GenericSerializer_1 ser_1 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (_ser_1_io_in_ready),
    .io_in_valid        (_TLDToBeat_io_beat_valid),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
    .io_in_bits_payload (_TLDToBeat_io_beat_bits_payload),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
    .io_in_bits_head    (_TLDToBeat_io_beat_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
    .io_in_bits_tail    (_TLDToBeat_io_beat_bits_tail),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:56:50]
    .io_out_ready       (io_ser_1_out_ready),
    .io_out_valid       (io_ser_1_out_valid),
    .io_out_bits_flit   (io_ser_1_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
  GenericSerializer_2 ser_2 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (/* unused */),
    .io_in_valid        (1'h0),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:36:16, :55:50, :57:50, :58:50, :65:23]
    .io_in_bits_payload (86'h0),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:57:50, :65:23]
    .io_in_bits_head    (_TLCToBeat_io_beat_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:57:50]
    .io_in_bits_tail    (1'h1),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:57:50, :65:23]
    .io_out_ready       (io_ser_2_out_ready),
    .io_out_valid       (io_ser_2_out_valid),
    .io_out_bits_flit   (io_ser_2_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
  GenericSerializer_3 ser_3 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
    .clock            (clock),
    .reset            (reset),
    .io_in_bits_head  (_TLBToBeat_io_beat_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:58:50]
    .io_in_bits_tail  (_TLBToBeat_io_beat_bits_tail),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:58:50]
    .io_out_ready     (io_ser_3_out_ready),
    .io_out_valid     (io_ser_3_out_valid),
    .io_out_bits_flit (io_ser_3_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
  GenericSerializer_2 ser_4 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (_ser_4_io_in_ready),
    .io_in_valid        (_TLAToBeat_io_beat_valid),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
    .io_in_bits_payload (_TLAToBeat_io_beat_bits_payload),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
    .io_in_bits_head    (_TLAToBeat_io_beat_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
    .io_in_bits_tail    (_TLAToBeat_io_beat_bits_tail),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:59:50]
    .io_out_ready       (io_ser_4_out_ready),
    .io_out_valid       (io_ser_4_out_valid),
    .io_out_bits_flit   (io_ser_4_out_bits_flit)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:65:23]
  TLEFromBeat TLEFromBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:74:28]
    .clock             (clock),
    .reset             (reset),
    .io_beat_ready     (_TLEFromBeat_io_beat_ready),
    .io_beat_valid     (_des_0_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_head (_des_0_io_out_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_tail (_des_0_io_out_bits_tail)	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:74:28]
  TLDFromBeat TLDFromBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:75:28]
    .clock                    (clock),
    .reset                    (reset),
    .io_protocol_ready        (auto_manager_in_d_ready),
    .io_protocol_valid        (auto_manager_in_d_valid),
    .io_protocol_bits_opcode  (auto_manager_in_d_bits_opcode),
    .io_protocol_bits_param   (auto_manager_in_d_bits_param),
    .io_protocol_bits_size    (_TLDFromBeat_io_protocol_bits_size),
    .io_protocol_bits_source  (auto_manager_in_d_bits_source),
    .io_protocol_bits_sink    (_TLDFromBeat_io_protocol_bits_sink),
    .io_protocol_bits_denied  (auto_manager_in_d_bits_denied),
    .io_protocol_bits_data    (auto_manager_in_d_bits_data),
    .io_protocol_bits_corrupt (auto_manager_in_d_bits_corrupt),
    .io_beat_ready            (_TLDFromBeat_io_beat_ready),
    .io_beat_valid            (_des_1_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_payload     (_des_1_io_out_bits_payload),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_head        (_des_1_io_out_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_tail        (_des_1_io_out_bits_tail)	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:75:28]
  TLCFromBeat TLCFromBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:76:28]
    .clock             (clock),
    .reset             (reset),
    .io_beat_ready     (_TLCFromBeat_io_beat_ready),
    .io_beat_valid     (_des_2_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_head (_des_2_io_out_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_tail (_des_2_io_out_bits_tail)	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:76:28]
  TLBFromBeat TLBFromBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:77:28]
    .clock             (clock),
    .reset             (reset),
    .io_beat_ready     (_TLBFromBeat_io_beat_ready),
    .io_beat_valid     (_des_3_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_head (_des_3_io_out_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_tail (_des_3_io_out_bits_tail)	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:77:28]
  TLAFromBeat TLAFromBeat (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:78:28]
    .clock                    (clock),
    .reset                    (reset),
    .io_protocol_ready        (auto_client_out_a_ready),
    .io_protocol_valid        (auto_client_out_a_valid),
    .io_protocol_bits_opcode  (auto_client_out_a_bits_opcode),
    .io_protocol_bits_param   (auto_client_out_a_bits_param),
    .io_protocol_bits_size    (_TLAFromBeat_io_protocol_bits_size),
    .io_protocol_bits_source  (auto_client_out_a_bits_source),
    .io_protocol_bits_address (_TLAFromBeat_io_protocol_bits_address),
    .io_protocol_bits_mask    (auto_client_out_a_bits_mask),
    .io_protocol_bits_data    (auto_client_out_a_bits_data),
    .io_protocol_bits_corrupt (auto_client_out_a_bits_corrupt),
    .io_beat_ready            (_TLAFromBeat_io_beat_ready),
    .io_beat_valid            (_des_4_io_out_valid),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_payload     (_des_4_io_out_bits_payload),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_head        (_des_4_io_out_bits_head),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_beat_bits_tail        (_des_4_io_out_bits_tail)	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:78:28]
  GenericDeserializer des_0 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .io_in_ready      (io_ser_0_in_ready),
    .io_in_valid      (io_ser_0_in_valid),
    .io_in_bits_flit  (io_ser_0_in_bits_flit),
    .io_out_ready     (_TLEFromBeat_io_beat_ready),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:74:28]
    .io_out_valid     (_des_0_io_out_valid),
    .io_out_bits_head (_des_0_io_out_bits_head),
    .io_out_bits_tail (_des_0_io_out_bits_tail)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  GenericDeserializer_1 des_1 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .clock               (clock),
    .reset               (reset),
    .io_in_ready         (io_ser_1_in_ready),
    .io_in_valid         (io_ser_1_in_valid),
    .io_in_bits_flit     (io_ser_1_in_bits_flit),
    .io_out_ready        (_TLDFromBeat_io_beat_ready),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:75:28]
    .io_out_valid        (_des_1_io_out_valid),
    .io_out_bits_payload (_des_1_io_out_bits_payload),
    .io_out_bits_head    (_des_1_io_out_bits_head),
    .io_out_bits_tail    (_des_1_io_out_bits_tail)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  GenericDeserializer_2 des_2 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .clock               (clock),
    .reset               (reset),
    .io_in_ready         (io_ser_2_in_ready),
    .io_in_valid         (io_ser_2_in_valid),
    .io_in_bits_flit     (io_ser_2_in_bits_flit),
    .io_out_ready        (_TLCFromBeat_io_beat_ready),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:76:28]
    .io_out_valid        (_des_2_io_out_valid),
    .io_out_bits_payload (/* unused */),
    .io_out_bits_head    (_des_2_io_out_bits_head),
    .io_out_bits_tail    (_des_2_io_out_bits_tail)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  GenericDeserializer_3 des_3 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .clock            (clock),
    .reset            (reset),
    .io_in_ready      (io_ser_3_in_ready),
    .io_in_valid      (io_ser_3_in_valid),
    .io_in_bits_flit  (io_ser_3_in_bits_flit),
    .io_out_ready     (_TLBFromBeat_io_beat_ready),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:77:28]
    .io_out_valid     (_des_3_io_out_valid),
    .io_out_bits_head (_des_3_io_out_bits_head),
    .io_out_bits_tail (_des_3_io_out_bits_tail)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  GenericDeserializer_2 des_4 (	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
    .clock               (clock),
    .reset               (reset),
    .io_in_ready         (io_ser_4_in_ready),
    .io_in_valid         (io_ser_4_in_valid),
    .io_in_bits_flit     (io_ser_4_in_bits_flit),
    .io_out_ready        (_TLAFromBeat_io_beat_ready),	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:78:28]
    .io_out_valid        (_des_4_io_out_valid),
    .io_out_bits_payload (_des_4_io_out_bits_payload),
    .io_out_bits_head    (_des_4_io_out_bits_head),
    .io_out_bits_tail    (_des_4_io_out_bits_tail)
  );	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:82:23]
  assign auto_manager_in_d_bits_size = _TLDFromBeat_io_protocol_bits_size[2:0];	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:75:28, :81:9]
  assign auto_manager_in_d_bits_sink = _TLDFromBeat_io_protocol_bits_sink[0];	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:75:28, :81:9]
  assign auto_client_out_a_bits_size = _TLAFromBeat_io_protocol_bits_size[2:0];	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:78:28, :81:9]
  assign auto_client_out_a_bits_address = _TLAFromBeat_io_protocol_bits_address[31:0];	// @[generators/testchipip/src/main/scala/serdes/TLSerdes.scala:78:28, :81:9]
endmodule

