set_property PACKAGE_PIN {R4} [get_ports {sys_clock}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sys_clock}]
set_property PACKAGE_PIN {V18} [get_ports {uart_rxd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_rxd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_rxd}]]]
set_property PACKAGE_PIN {AA19} [get_ports {uart_txd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_txd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_txd}]]]
set_property PACKAGE_PIN {T14} [get_ports {led_0}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_0}]
set_property PACKAGE_PIN {T15} [get_ports {led_1}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_1}]
set_property PACKAGE_PIN {T16} [get_ports {led_2}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_2}]
set_property PACKAGE_PIN {U16} [get_ports {led_3}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_3}]
set_property PACKAGE_PIN {V15} [get_ports {led_4}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_4}]
set_property PACKAGE_PIN {W16} [get_ports {led_5}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_5}]
set_property PACKAGE_PIN {W15} [get_ports {led_6}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_6}]
set_property PACKAGE_PIN {Y13} [get_ports {led_7}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_7}]
set_property BOARD_PIN {reset} [get_ports {reset}]
#set_property PACKAGE_PIN {AB22} [get_ports {serial_tl_clock_out}]
#set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_clock_out}]
#set_property PACKAGE_PIN {AB21} [get_ports {serial_tl_out_valid}]
#set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_out_valid}]
#set_property PACKAGE_PIN {AB20} [get_ports {serial_tl_out_ready}]
#set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_out_ready}]
#set_property PACKAGE_PIN {AB18} [get_ports {serial_tl_in_valid}]
#set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_in_valid}]
#set_property PACKAGE_PIN {Y21} [get_ports {serial_tl_in_ready}]
#set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_in_ready}]
#set_property PACKAGE_PIN {AA21} [get_ports {serial_tl_out_bits_phit}]
#set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_out_bits_phit}]
#set_property PACKAGE_PIN {V8} [get_ports {serial_tl_in_bits_phit}]
#set_property IOSTANDARD {LVCMOS33} [get_ports {serial_tl_in_bits_phit}]
set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS12 } [get_ports { serial_tl_clock_out }]; #IO_L13P_T2_MRCC_15 Sch=fmc_la00_cc_p
set_property -dict { PACKAGE_PIN M18   IOSTANDARD LVCMOS12 } [get_ports { serial_tl_out_valid }]; #IO_L16P_T2_A28_15 Sch=fmc_la_p[02]
set_property -dict { PACKAGE_PIN N20   IOSTANDARD LVCMOS12 } [get_ports { serial_tl_out_ready }]; #IO_L18P_T2_A24_15 Sch=fmc_la_p[04]
set_property -dict { PACKAGE_PIN N18   IOSTANDARD LVCMOS12 } [get_ports { serial_tl_in_valid }]; #IO_L17P_T2_A26_15 Sch=fmc_la_p[03]
set_property -dict { PACKAGE_PIN M15   IOSTANDARD LVCMOS12 } [get_ports { serial_tl_in_ready }]; #IO_L24P_T3_RS1_15 Sch=fmc_la_p[08]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS12 } [get_ports { serial_tl_out_bits_phit }]; #IO_L20P_T3_A20_15 Sch=fmc_la_p[07]
set_property -dict { PACKAGE_PIN L19   IOSTANDARD LVCMOS12 } [get_ports { serial_tl_in_bits_phit }]; #IO_L14P_T2_SRCC_15 Sch=fmc_la_p[12]
